Repository meilisearch/meilisearch, pull requests merged in 2020-10, with the labels that each got.

#989 URL encode search in web UI
  meilisearch-http/public/interface.html
Labels: Hacktoberfest

#1007 fix clippy errors
  meilisearch-core/src/database.rs
  meilisearch-http/src/dump.rs
  meilisearch-http/src/helpers/meilisearch.rs
  meilisearch-http/src/snapshot.rs
  meilisearch-schema/src/schema.rs
Labels: RFR

#978 Add code coverage
  .github/workflows/coverage.yml
Labels: RFR

#946 Sort displayedAttributes field
  CHANGELOG.md
  meilisearch-core/src/database.rs
  meilisearch-core/src/settings.rs
  meilisearch-core/src/store/main.rs
  meilisearch-http/src/routes/setting.rs
  meilisearch-http/src/routes/stats.rs
  meilisearch-http/tests/index.rs
  meilisearch-http/tests/settings.rs
Labels: RFR, meilisearch-http

#979 Add dependabot with a monthly update
  .github/dependabot.yml
Labels: RFR

#984 Add test search
  meilisearch-http/tests/search.rs
Labels: RFR

#914 lazily create an index on documents push
  Cargo.lock
  meilisearch-http/src/data.rs
  meilisearch-http/src/routes/document.rs
  meilisearch-http/src/routes/setting.rs
  meilisearch-http/src/routes/stop_words.rs
  meilisearch-http/src/routes/synonym.rs
  meilisearch-http/tests/common.rs
  meilisearch-http/tests/documents_add.rs
  meilisearch-http/tests/lazy_index_creation.rs
Labels: RFR, meilisearch-http

#1001 Fix settings bug
  meilisearch-core/src/facets.rs
  meilisearch-core/src/serde/deserializer.rs
  meilisearch-core/src/store/mod.rs
  meilisearch-core/src/update/documents_addition.rs
  meilisearch-http/tests/search.rs
  meilisearch-http/tests/settings.rs
  meilisearch-schema/src/schema.rs
Labels: RFR

#1026 refactor /health
  meilisearch-http/src/routes/health.rs
  meilisearch-http/tests/health.rs
Labels: Hacktoberfest, breaking, good first issue, meilisearch-http

#1028 Clean external contributions
  CHANGELOG.md
  Cargo.lock
  meilisearch-core/src/database.rs
  meilisearch-http/tests/index.rs
Labels: RFR

#1008 Dump info
  meilisearch-http/src/data.rs
  meilisearch-http/src/dump.rs
  meilisearch-http/src/error.rs
  meilisearch-http/src/main.rs
  meilisearch-http/src/option.rs
  meilisearch-http/src/routes/dump.rs
  meilisearch-http/src/snapshot.rs
  meilisearch-http/tests/common.rs
  meilisearch-http/tests/dump.rs
Labels: RFR, meilisearch-http
