Repository meilisearch/meilisearch, pull requests merged in 2021-02, with the labels that each got.

#1184 normalize synonyms during indexation
  meilisearch-core/src/update/settings_update.rs
  meilisearch-http/tests/search_settings.rs
Labels: breaking, type:enhancement

#1176 fix race condition in document addition
  meilisearch-core/src/update/documents_addition.rs
  meilisearch-core/src/update/mod.rs
  meilisearch-http/src/dump.rs
  meilisearch-http/src/routes/document.rs
  meilisearch-http/tests/index_update.rs
Labels: breaking, type:bug

#1172 Fix atomic snapshot creation
  Cargo.lock
  meilisearch-http/Cargo.toml
  meilisearch-http/src/helpers/compression.rs
Labels: type:enhancement, type:internals

#1224 fix synonyms normalization
  meilisearch-core/src/update/settings_update.rs
  meilisearch-http/tests/settings.rs
Labels: type:bug

#1253 fix line break
  README.md
Labels: type:enhancement
