Repository meilisearch/meilisearch, pull requests merged in 2022-10, with the labels that each got.

#2831 Make clippy happy
  meilisearch-lib/src/tasks/task_store/mod.rs
Labels: maintenance

#2827 Upgrade to alpine 3.16
  Dockerfile
Labels: maintenance

#2819 Replace a meaningless serde message
  meilisearch-http/tests/documents/add_documents.rs
  meilisearch-lib/src/document_formats.rs
Labels: error handler

#2845 Fix broken link in contributing.md
  CONTRIBUTING.md
Labels: documentation

#2848 v0.29.0: bring `stable` changes into `main`
  Cargo.lock
  Cargo.toml
  meilisearch-auth/src/lib.rs
  meilisearch-http/Cargo.toml
  meilisearch-http/src/extractors/authentication/mod.rs
  meilisearch-http/src/routes/indexes/mod.rs
  meilisearch-http/tests/auth/authorization.rs
  meilisearch-lib/src/index/updates.rs
Labels: maintenance

#2852 Fix milestone-workflow.yml
  .github/workflows/milestone-workflow.yml
Labels: maintenance, skip changelog, github actions

#2853 Fix milestone-workflow.yml (when adding labels to PRs)
  .github/workflows/milestone-workflow.yml
Labels: maintenance, skip changelog, github actions

#2847 Upgrade dependencies
  Cargo.lock
  meilisearch-auth/Cargo.toml
  meilisearch-auth/src/action.rs
  meilisearch-auth/src/store.rs
  meilisearch-http/Cargo.toml
  meilisearch-http/src/analytics/segment_analytics.rs
  meilisearch-lib/Cargo.toml
  meilisearch-types/Cargo.toml
Labels: dependencies

#2839 Update internal CLI documentation
  meilisearch-http/src/option.rs
  meilisearch-lib/src/options.rs
Labels: documentation

#2868 Uncomment cache steps in Github CI
  .github/workflows/rust.yml
Labels: maintenance

#2896 Fix CI to send signal to Cloud team
  .github/workflows/publish-docker-images.yml
Labels: maintenance, github actions

#2913 download-latest: some refactoring
  download-latest.sh
Labels: tooling, maintenance

#2928 Improve default config file
  config.toml
Labels: documentation

#2951 Update mini-dashboard to v0.2.3
  meilisearch-http/Cargo.toml
Labels: tooling

#2922 Add new error when using /keys without masterkey set
  meilisearch-http/src/extractors/authentication/error.rs
  meilisearch-http/src/extractors/authentication/mod.rs
  meilisearch-http/tests/auth/api_keys.rs
  meilisearch-types/src/error.rs
Labels: breaking change

#2993 Reconsider the Windows tests
  meilisearch-http/tests/auth/tenant_token.rs
  meilisearch-http/tests/dumps/mod.rs
  meilisearch-http/tests/index/delete_index.rs
Labels: enhancement, windows

#3001 Implement Uuid codec for heed
  index-scheduler/src/index_mapper.rs
  index-scheduler/src/lib.rs
  index-scheduler/src/uuid_codec.rs
Labels: hacktoberfest-accepted
