Repository meilisearch/meilisearch, pull requests merged in 2022-12, with the labels that each got.

#3172 Add CI to push a latest git tag for every stable Meilisearch release
  .github/workflows/latest-git-tag.yml
  .github/workflows/publish-docker-images.yml
Labels: maintenance, github actions

#3169 Improve download-latest.sh script: integrate apple-silicon binary
  download-latest.sh
Labels: tooling

#3186 Update mini-dashboard to v0.2.4
  meilisearch-http/Cargo.toml
Labels: tooling

#3189 Upgrade alpine 3.16 to 3.17
  Dockerfile
Labels: dependencies, tooling

#3188 re-enable the dump test on the dates
  dump/src/reader/compat/v1_to_v2.rs
  dump/src/reader/mod.rs
  dump/src/reader/v1/mod.rs
Labels: enhancement, maintenance, skip changelog

#3175 Rename dump command from --dumps-dir to --dump-dir
  config.toml
  meilisearch-http/src/analytics/segment_analytics.rs
  meilisearch-http/src/lib.rs
  meilisearch-http/src/option.rs
  meilisearch-http/tests/common/server.rs
Labels: breaking change

#3197 Revert "Upgrade alpine 3.16 to 3.17"
  Dockerfile
Labels: bug, maintenance, skip changelog

#3190 Fix the dump date-import of the dumpv4
  dump/src/reader/mod.rs
  dump/src/reader/v4/mod.rs
  dump/src/reader/v4/tasks.rs
Labels: bug

#3128 Bumps cargo_toml version to most up to date
  Cargo.lock
  meilisearch-http/Cargo.toml
Labels: dependencies, maintenance

#3204 Bring back v0.30.1 changes to `main`
  Cargo.lock
  dump/Cargo.toml
  dump/src/writer.rs
  file-store/Cargo.toml
  index-scheduler/Cargo.toml
  index-scheduler/src/index_mapper.rs
  index-scheduler/src/lib.rs
  index-scheduler/src/utils.rs
  meili-snap/Cargo.toml
  meilisearch-auth/Cargo.toml
  meilisearch-http/Cargo.toml
  meilisearch-types/Cargo.toml
  permissive-json-pointer/Cargo.toml
Labels: skip changelog

#3207 Add release check when starting latest CI
  .github/scripts/is-latest-release.sh
  .github/workflows/latest-git-tag.yml
Labels: maintenance, github actions

#3208 Stop snapshotting the version of meilisearch in the dump
  dump/src/writer.rs
Labels: maintenance

#3213 Fix the instance-uid in the data.ms
  meilisearch-http/src/analytics/segment_analytics.rs
Labels: bug

#3215 Use nightly in cargo fmt
  .github/workflows/rust.yml
Labels: maintenance, skip changelog

#3212 Setup COMMIT_SHA and COMMIT_DATE build args in the Docker image
  .github/workflows/publish-docker-images.yml
  Dockerfile
Labels: maintenance, github actions

#3229 Add a nightly CI: create every day a `nightly` Docker tag based on the latest commit on `main`
  .github/scripts/is-latest-release.sh
  .github/workflows/coverage.yml
  .github/workflows/latest-git-tag.yml
  .github/workflows/milestone-workflow.yml
  .github/workflows/publish-deb-brew-pkg.yml
  .github/workflows/publish-docker-images.yml
Labels: tooling, maintenance, github actions

#3224 Fix update-cargo-toml-version.yml
  .github/workflows/update-cargo-toml-version.yml
Labels: bug, github actions

#3223 Bring back release-v0.30.2 changes into main
  Cargo.lock
  meilisearch-types/Cargo.toml
  meilisearch/src/analytics/segment_analytics.rs
Labels: maintenance, skip changelog

#3234 Update README.md
  README.md
Labels: documentation

#3237 Fix the cli flags related to the import of dump and snapshot.
  meilisearch-http/src/lib.rs
Labels: bug

#3241 Remove core mention
  .github/workflows/create-issue-dependencies.yml
  .github/workflows/milestone-workflow.yml
Labels: skip changelog

#3247 Re-add push in docker CI
  .github/workflows/publish-docker-images.yml
Labels: bug, github actions

#3249 Bring back changes from release-v0.30.3 to main
  Cargo.lock
  meilisearch-types/Cargo.toml
  meilisearch/src/lib.rs
Labels: skip changelog

#3258 Bump milli to v0.37.4
  Cargo.lock
  meilisearch-types/Cargo.toml
Labels: skip changelog

#3262 Clippy fixes after updating Rust to v1.66
  dump/src/reader/v4/mod.rs
  dump/src/writer.rs
  index-scheduler/src/batch.rs
  index-scheduler/src/lib.rs
  meili-snap/src/lib.rs
  meilisearch-auth/src/dump.rs
  meilisearch-types/src/versioning.rs
  meilisearch/src/analytics/mod.rs
Labels: skip changelog

#3261 Use ubuntu-18.04 container instead of GitHub hosted actions
  .github/workflows/flaky.yml
  .github/workflows/publish-binaries.yml
  .github/workflows/publish-deb-brew-pkg.yml
  .github/workflows/rust.yml
  .github/workflows/update-cargo-toml-version.yml
Labels: maintenance, github actions

#3276 README: Replace Slack link with Discord
  README.md
Labels: maintenance
