Repository meilisearch/meilisearch, pull requests merged in 2022-07, with the labels that each got.

#2539 Update Docker credentials
  .github/workflows/publish-docker-images.yml
Labels: maintenance

#2585 Add CI creates issue updating dependencies
  .github/workflows/create-issue-dependencies.yml
Labels: dependencies, maintenance, github_actions

#2589 Update create-issue-dependencies.yml
  .github/workflows/create-issue-dependencies.yml
Labels: skip changelog

#2592 Chores: Add a dedicated section for Language Support in the issue template
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation, skip changelog

#2625 Update link to Cloud beta form
  README.md
Labels: documentation

#2630 Update version for next release (v0.28.1)
  Cargo.lock
  meilisearch-auth/Cargo.toml
  meilisearch-http/Cargo.toml
  meilisearch-lib/Cargo.toml
  meilisearch-types/Cargo.toml
  permissive-json-pointer/Cargo.toml
Labels: skip changelog

#2631 Update mini-dashboard to v0.2.1
  meilisearch-http/Cargo.toml
Labels: tooling

#2633 Fix highlight issue by updating milli to v0.31.2
  Cargo.lock
  meilisearch-auth/Cargo.toml
  meilisearch-lib/Cargo.toml
Labels: bug
