Repository meilisearch/meilisearch, pull requests merged in 2022-11, with the labels that each got.

#3019 Fix error code of the "duplicate index found" error on the index swap route
  index-scheduler/src/error.rs
Labels: bug

#3015 Replace deprecated set-output in GitHub actions
  .github/workflows/milestone-workflow.yml
  .github/workflows/publish-binaries.yml
  .github/workflows/publish-docker-images.yml
Labels: maintenance, hacktoberfest-accepted

#3061 Name spawned threads
  index-scheduler/src/index_mapper.rs
  index-scheduler/src/lib.rs
  meilisearch-http/src/lib.rs
  meilisearch-http/src/option.rs
Labels: maintenance

#3041 Add `workflow_dispatch` to flaky.yml
  .github/workflows/flaky.yml
Labels: maintenance, github actions

#3083 Add `workflow_dispatch` to flaky.yml
  .github/workflows/flaky.yml
Labels: maintenance, skip changelog

#3099 Add a dispatch to the publish binaries workflow
  .github/workflows/publish-binaries.yml
Labels: maintenance, github actions

#3100 Add a dispatch to the publish binaries workflow
  .github/workflows/publish-binaries.yml
Labels: maintenance, github actions

#3105 Fix publish release CI
  .github/workflows/publish-binaries.yml
Labels: bug, maintenance, github actions

#3136 Fix no master key error
  meilisearch-http/src/extractors/authentication/mod.rs
  meilisearch-http/tests/auth/api_keys.rs
Labels: bug

#3161 « Fix » dump tests
  dump/src/reader/compat/v5_to_v6.rs
  dump/src/reader/mod.rs
Labels: maintenance
