Repository meilisearch/meilisearch, pull requests merged in 2022-06, with the labels that each got.

#2438 Refine keys api
  Cargo.lock
  meilisearch-auth/Cargo.toml
  meilisearch-auth/src/action.rs
  meilisearch-auth/src/dump.rs
  meilisearch-auth/src/error.rs
  meilisearch-auth/src/key.rs
  meilisearch-auth/src/lib.rs
  meilisearch-auth/src/store.rs
  meilisearch-error/src/lib.rs
  meilisearch-http/Cargo.toml
  meilisearch-http/src/extractors/authentication/mod.rs
  meilisearch-http/src/routes/api_key.rs
  meilisearch-http/tests/auth/api_keys.rs
  meilisearch-http/tests/auth/authorization.rs
  meilisearch-http/tests/auth/mod.rs
  meilisearch-http/tests/auth/tenant_token.rs
  meilisearch-http/tests/common/index.rs
  meilisearch-lib/Cargo.toml
  meilisearch-lib/src/dump/loaders/v4.rs
Labels: breaking change

#2445 Seek-based tasks list
  Cargo.lock
  meilisearch-http/src/routes/tasks.rs
  meilisearch-http/src/task.rs
  meilisearch-http/tests/dumps/mod.rs
  meilisearch-lib/Cargo.toml
  meilisearch-lib/src/tasks/batch.rs
  meilisearch-lib/src/tasks/scheduler.rs
  meilisearch-lib/src/tasks/task.rs
  meilisearch-lib/src/tasks/task_store/mod.rs
  meilisearch-lib/src/tasks/task_store/store.rs
Labels: breaking change

#2474 feat(auth): remove `dumps.get` action from keys
  meilisearch-auth/src/action.rs
  meilisearch-http/tests/auth/api_keys.rs
Labels: breaking change

#2468 Update milli 0.29
  Cargo.lock
  meilisearch-auth/Cargo.toml
  meilisearch-http/tests/common/index.rs
  meilisearch-http/tests/documents/get_documents.rs
  meilisearch-http/tests/settings/get_settings.rs
  meilisearch-lib/Cargo.toml
  meilisearch-lib/src/index/index.rs
  meilisearch-lib/src/index/search.rs
Labels: enhancement, dependencies

#2491 Improve Docker CIs
  .github/workflows/publish-docker-images.yml
  .github/workflows/publish-docker-latest.yml
Labels: maintenance

#2494 Introduce the new faceting and pagination settings
  Cargo.lock
  meilisearch-auth/Cargo.toml
  meilisearch-http/src/routes/indexes/settings.rs
  meilisearch-http/tests/dumps/mod.rs
  meilisearch-http/tests/search/mod.rs
  meilisearch-http/tests/settings/get_settings.rs
  meilisearch-lib/Cargo.toml
  meilisearch-lib/src/index/index.rs
  meilisearch-lib/src/index/search.rs
  meilisearch-lib/src/index/updates.rs
Labels: impacts docs, impacts integrations

#2502 test dump v5
  meilisearch-http/tests/assets/v5_v0.28.0_test_dump.dump
  meilisearch-http/tests/common/server.rs
  meilisearch-http/tests/dumps/data.rs
  meilisearch-http/tests/dumps/mod.rs
Labels: maintenance

#2519 Use nightly for cargo fmt in CI
  .github/workflows/rust.yml
Labels: maintenance

#2520 Use nightly for cargo fmt in CI (for `release-v0.28.0` branch)
  .github/workflows/rust.yml
Labels: maintenance

#2537 Change information place regarding release assets
  .github/workflows/README.md
  CONTRIBUTING.md
Labels: documentation

#2530 Check the version in Cargo.toml before publishing
  .github/scripts/check-release.sh
  .github/scripts/is-latest-release.sh
  .github/workflows/publish-binaries.yml
  .github/workflows/publish-deb-brew-pkg.yml
  .github/workflows/publish-docker-images.yml
  Cargo.lock
  permissive-json-pointer/Cargo.toml
Labels: tooling

#2561 Add dependabot for GHA
  .github/dependabot.yml
Labels: maintenance
