Repository meilisearch/meilisearch, pull requests merged in 2022-08, with the labels that each got.

#2677 Hide the batch_uid field from the tasks route
  meilisearch-http/src/task.rs
Labels: impacts docs, breaking change

#2678 Accept either an array of documents or a single document
  Cargo.lock
  meilisearch-http/tests/documents/add_documents.rs
  meilisearch-lib/Cargo.toml
  meilisearch-lib/src/document_formats.rs
Labels: bug

#2636 Upgrade milli to v0.33.0
  Cargo.lock
  meilisearch-auth/Cargo.toml
  meilisearch-http/Cargo.toml
  meilisearch-http/src/analytics/segment_analytics.rs
  meilisearch-http/src/routes/indexes/search.rs
  meilisearch-http/tests/search/errors.rs
  meilisearch-lib/Cargo.toml
  meilisearch-lib/src/error.rs
  meilisearch-lib/src/index/mod.rs
  meilisearch-lib/src/index/search.rs
  meilisearch-lib/src/index_controller/mod.rs
Labels: breaking change

#2692 Slight changes for prometheus metrics
  grafana-dashboards/dashboard.json
  meilisearch-http/src/metrics.rs
  meilisearch-http/src/routes/mod.rs
Labels: enhancement

#2717 Disable LTO due to compilation failures on some platforms
  Cargo.toml
Labels: bug, performance

#2719 Update ubuntu-18.04 to 20.04
  .github/workflows/coverage.yml
  .github/workflows/flaky.yml
  .github/workflows/publish-binaries.yml
  .github/workflows/publish-deb-brew-pkg.yml
  .github/workflows/rust.yml
  bors.toml
Labels: maintenance

#2726 Add dry run for publishing binaries: check the compilation works
  .github/workflows/publish-binaries.yml
Labels: maintenance, github_actions
