Repository meilisearch/meilisearch, pull requests merged in 2022-09, with the labels that each got.

#2733 Move if conditions to the steps and not to the whole job
  .github/workflows/publish-binaries.yml
Labels: maintenance

#2741 Add CI to update the Meilisearch version in Cargo.toml files
  .github/workflows/update-cargo-toml-version.yml
Labels: maintenance

#2739 Add CI manifest to automate some steps when closing/creating a Milestone
  .github/workflows/milestone-workflow.yml
Labels: maintenance

#2740 Update checkout v2 to v3 in CI manifests and use a unique GitHub PAT
  .github/workflows/create-issue-dependencies.yml
  .github/workflows/publish-binaries.yml
  .github/workflows/publish-deb-brew-pkg.yml
  .github/workflows/publish-docker-images.yml
Labels: maintenance, skip changelog

#2744 Minor fixes in the just added update-version CI
  .github/workflows/update-cargo-toml-version.yml
Labels: skip changelog

#2770 Update milli 0.33.4
  Cargo.lock
  meilisearch-auth/Cargo.toml
  meilisearch-lib/Cargo.toml
Labels: bug, milli

#2790 Improve Docker CI for cloud team
  .github/workflows/publish-docker-images.yml
Labels: maintenance, github actions

#2793 Update CONTRIBUTING.md for Hacktoberfest
  CONTRIBUTING.md
Labels: skip changelog

#2794 Update README.md with Hacktoberfest section
  README.md
Labels: documentation, skip changelog
