Repository meilisearch/meilisearch, pull requests merged in 2023-09, with the labels that each got.

#4016 Define the full Homebrew formula path
  .github/workflows/publish-apt-brew-pkg.yml
Labels: bug, maintenance

#4033 Fix thai synonyms
  milli/src/update/index_documents/extract/extract_docid_word_positions.rs
  milli/src/update/settings.rs
Labels: bug

#4039 Fix multiple vectors dimensions
  milli/src/update/index_documents/extract/mod.rs
  milli/src/update/index_documents/mod.rs
Labels: bug

#4041 Register the swap indexe task in a spawn blocking to be sure to never…
  meilisearch/src/routes/swap_indexes.rs
Labels: bug, maintenance

#4005 Improve test-suite.yml for CI failing when disabling tokenization
  .github/workflows/test-suite.yml
Labels: maintenance

#4051 Implement the snapshots on demand
  meilisearch-auth/src/store.rs
  meilisearch-types/src/keys.rs
  meilisearch/src/routes/mod.rs
  meilisearch/src/routes/snapshot.rs
  meilisearch/tests/auth/api_keys.rs
  meilisearch/tests/auth/authorization.rs
  meilisearch/tests/auth/errors.rs
  meilisearch/tests/auth/mod.rs
  meilisearch/tests/auth/tenant_token.rs
  meilisearch/tests/auth/tenant_token_multi_search.rs
  meilisearch/tests/common/index.rs
  meilisearch/tests/common/mod.rs
  meilisearch/tests/common/server.rs
  meilisearch/tests/common/service.rs
  meilisearch/tests/content_type.rs
  meilisearch/tests/documents/add_documents.rs
  meilisearch/tests/documents/delete_documents.rs
  meilisearch/tests/documents/errors.rs
  meilisearch/tests/documents/get_documents.rs
  meilisearch/tests/documents/update_documents.rs
  meilisearch/tests/dumps/mod.rs
  meilisearch/tests/features/mod.rs
  meilisearch/tests/index/create_index.rs
  meilisearch/tests/index/delete_index.rs
  meilisearch/tests/index/errors.rs
  meilisearch/tests/index/stats.rs
  meilisearch/tests/index/update_index.rs
  meilisearch/tests/search/errors.rs
  meilisearch/tests/search/facet_search.rs
  meilisearch/tests/search/formatted.rs
  meilisearch/tests/search/geo.rs
  meilisearch/tests/search/mod.rs
  meilisearch/tests/search/multi.rs
  meilisearch/tests/search/pagination.rs
  meilisearch/tests/search/restrict_searchable.rs
  meilisearch/tests/settings/distinct.rs
  meilisearch/tests/settings/errors.rs
  meilisearch/tests/settings/get_settings.rs
  meilisearch/tests/settings/tokenizer_customization.rs
  meilisearch/tests/snapshot/mod.rs
  meilisearch/tests/stats/mod.rs
  meilisearch/tests/swap_indexes/errors.rs
  meilisearch/tests/swap_indexes/mod.rs
  meilisearch/tests/tasks/mod.rs
Labels: enhancement

#4053 Fix the stats of the documents deletion by filter
  index-scheduler/src/batch.rs
  meilisearch/tests/documents/delete_documents.rs
Labels: bug

#4056 Rewrite segment_analytics module with the destructuring syntax
  meilisearch/src/analytics/segment_analytics.rs
Labels: maintenance

#4069 Revert the fix on the filters about escaping sequences
  Cargo.lock
  filter-parser/Cargo.toml
  filter-parser/src/error.rs
  filter-parser/src/lib.rs
  filter-parser/src/value.rs
Labels: breaking change

#4074 Enable analytics in debug builds
  meilisearch/src/analytics/mod.rs
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/option.rs
  meilisearch/tests/common/server.rs
Labels: maintenance
