Repository meilisearch/meilisearch, pull requests merged in 2023-02, with the labels that each got.

#3445 Bump milli to v0.41.1
  Cargo.lock
  meilisearch-types/Cargo.toml
Labels: milli

#3436 Add more detailed contribution instructions for tests
  CONTRIBUTING.md
Labels: documentation, skip changelog

#3040 feat: create a preview environment for every PR using Uffizzi
  .github/uffizzi/Dockerfile
  .github/uffizzi/docker-compose.uffizzi.yml
  .github/uffizzi/nginx/nginx.conf
  .github/workflows/uffizzi-build.yml
  .github/workflows/uffizzi-preview-deploy.yml
Labels: tooling

#3451 Pin Rust version in Clippy job
  .github/workflows/create-issue-dependencies.yml
  .github/workflows/rust.yml
Labels: maintenance, github actions

#3199 Fixup dumps-destination -> dump-directory section header in help link
  config.toml
Labels: skip changelog

#3479 Unify "Bad latitude" & "Bad longitude" errors
  milli/src/asc_desc.rs
  milli/src/search/facet/filter.rs
  milli/src/search/facet/mod.rs
Labels: bug, error handler

#3495 Add tests with rust nightly in CI
  .github/workflows/rust.yml
Labels: maintenance, github actions

#3492 Bump deserr
  Cargo.lock
  meilisearch-types/Cargo.toml
  meilisearch-types/src/deserr/error_messages.rs
  meilisearch-types/src/deserr/mod.rs
  meilisearch-types/src/deserr/query_params.rs
  meilisearch-types/src/error.rs
  meilisearch-types/src/index_uid.rs
  meilisearch-types/src/index_uid_pattern.rs
  meilisearch-types/src/keys.rs
  meilisearch-types/src/settings.rs
  meilisearch-types/src/star_or.rs
  meilisearch/Cargo.toml
  meilisearch/src/extractors/json.rs
  meilisearch/src/extractors/mod.rs
  meilisearch/src/extractors/query_parameters.rs
  meilisearch/src/routes/api_key.rs
  meilisearch/src/routes/indexes/documents.rs
  meilisearch/src/routes/indexes/mod.rs
  meilisearch/src/routes/indexes/search.rs
  meilisearch/src/routes/indexes/settings.rs
  meilisearch/src/routes/swap_indexes.rs
  meilisearch/src/routes/tasks.rs
  meilisearch/src/search.rs
  meilisearch/tests/auth/errors.rs
  milli/Cargo.toml
  milli/src/update/settings.rs
Labels: enhancement, error handler

#3501 Update milli 0.41.2
  Cargo.lock
  dump/Cargo.toml
  file-store/Cargo.toml
  index-scheduler/Cargo.toml
  meili-snap/Cargo.toml
  meilisearch-auth/Cargo.toml
  meilisearch-types/Cargo.toml
  meilisearch/Cargo.toml
  permissive-json-pointer/Cargo.toml
Labels: bug

#3490 Fix attributes set candidates
  milli/src/search/criteria/attribute.rs
Labels: bug, milli, skip changelog, v1.0.1

#3499 Use the workspace inheritance
  .github/scripts/check-release.sh
  .github/workflows/update-cargo-toml-version.yml
  Cargo.lock
  Cargo.toml
  benchmarks/Cargo.toml
  dump/Cargo.toml
  file-store/Cargo.toml
  filter-parser/Cargo.toml
  flatten-serde-json/Cargo.toml
  index-scheduler/Cargo.toml
  json-depth-checker/Cargo.toml
  meili-snap/Cargo.toml
  meilisearch-auth/Cargo.toml
  meilisearch-types/Cargo.toml
  meilisearch/Cargo.toml
  milli/Cargo.toml
  permissive-json-pointer/Cargo.toml
Labels: enhancement, maintenance

#3514 Bump version of mini-dashboard to v0.2.6
  meilisearch/Cargo.toml
Labels: tooling

#3505 Csv delimiter
  Cargo.lock
  meilisearch-types/Cargo.toml
  meilisearch-types/src/document_formats.rs
  meilisearch-types/src/error.rs
  meilisearch/Cargo.toml
  meilisearch/src/error.rs
  meilisearch/src/routes/indexes/documents.rs
  meilisearch/tests/common/index.rs
  meilisearch/tests/common/service.rs
  meilisearch/tests/documents/add_documents.rs
  meilisearch/tests/documents/errors.rs
  milli/Cargo.toml
Labels: enhancement, impacts docs, error handler

#3496 Fix metrics feature
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/lib.rs
  meilisearch/src/route_metrics.rs
Labels: bug, maintenance

#3482 Optimize meilisearch uffizzi build
  .github/uffizzi/Dockerfile
  .github/workflows/uffizzi-build.yml
  .github/workflows/uffizzi-preview-deploy.yml
Labels: tooling

#3528 Fix a bug where the filestore could try to parse its own tmp file and fail
  file-store/src/lib.rs
Labels: bug

#3534 Update the csv error code from InvalidIndexCsvDelimiter to InvalidDocumentCsvDelimiter
  meilisearch-types/src/error.rs
  meilisearch/src/routes/indexes/documents.rs
  meilisearch/tests/documents/errors.rs
Labels: error handler

#3530 Fix highlighter bug
  meilisearch/src/search.rs
  meilisearch/tests/search/formatted.rs
Labels: bug

#3524 Update the metrics route
  config.toml
  meilisearch/Cargo.toml
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/lib.rs
  meilisearch/src/middleware.rs
  meilisearch/src/option.rs
  meilisearch/src/routes/metrics.rs
  meilisearch/src/routes/mod.rs
  meilisearch/tests/auth/authorization.rs
  meilisearch/tests/common/server.rs
Labels: experimental feature

#3537 fix a bug where the filestore could try to parse its own tmp file and fail (main)
  file-store/src/lib.rs
Labels: bug, skip changelog

#3519 Update comments in version bump CI
  .github/workflows/update-cargo-toml-version.yml
Labels: skip changelog, github actions

#3538 Improve the api key of the metrics
  meilisearch/src/routes/metrics.rs
  meilisearch/tests/auth/authorization.rs
Labels: experimental feature

#3539 Update migration link to the docs
  meilisearch-types/src/versioning.rs
Labels: documentation
