Repository meilisearch/meilisearch, pull requests merged in 2023-08, with the labels that each got.

#3981 Truncate the normalized long facets used in the search for facet value
  milli/src/lib.rs
  milli/src/update/facet/mod.rs
  milli/src/update/index_documents/extract/extract_facet_string_docids.rs
Labels: bug

#3986 Fix geo bounding box with strings
  dump/src/reader/snapshots/dump__reader__test__import_dump_v1-10.snap
  dump/src/reader/snapshots/dump__reader__test__import_dump_v1-4.snap
  dump/src/reader/snapshots/dump__reader__test__import_dump_v1-7.snap
  meili-snap/src/lib.rs
  meilisearch/tests/search/geo.rs
  milli/src/index.rs
  milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs
  milli/src/update/index_documents/extract/mod.rs
Labels: bug, geo search

#3989 Improve test suite CI for manual trigger events
  .github/workflows/test-suite.yml
Labels: maintenance

#3976 Fix the get stats method
  index-scheduler/src/lib.rs
Labels: bug, experimental feature

#3987 Update dependencies for v1.4
  .github/workflows/test-suite.yml
  Cargo.lock
  fuzzers/Cargo.toml
  meilisearch-types/Cargo.toml
  meilisearch/Cargo.toml
  milli/Cargo.toml
Labels: dependencies

#4019 Bringing back changes from `v1.3.2` onto `main`
  Cargo.lock
  Cargo.toml
  meilisearch/src/search.rs
  milli/Cargo.toml
  milli/src/lib.rs
  milli/src/search/new/bucket_sort.rs
  milli/src/update/index_documents/extract/extract_vector_points.rs
Labels: v1.3.2
