Repository meilisearch/meilisearch, pull requests merged in 2023-06, with the labels that each got.

#3789 Improve the metrics
  assets/grafana-dashboard.json
  assets/prometheus-basic-scraper.yml
  grafana-dashboards/dashboard.json
  index-scheduler/src/index_mapper/mod.rs
  index-scheduler/src/lib.rs
  meilisearch-auth/src/lib.rs
  meilisearch-auth/src/store.rs
  meilisearch/src/metrics.rs
  meilisearch/src/middleware.rs
  meilisearch/src/routes/metrics.rs
  meilisearch/src/routes/mod.rs
Labels: breaking change, experimental feature

#3819 Remove the `docid_word_positions` database
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/snapshot_tests.rs
  milli/src/update/clear_documents.rs
  milli/src/update/delete_documents.rs
  milli/src/update/index_documents/extract/mod.rs
  milli/src/update/index_documents/helpers/merge_functions.rs
  milli/src/update/index_documents/helpers/mod.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/typed_chunk.rs
Labels: performance, indexing

#3813 Fix SDK CI for scheduled jobs
  .github/workflows/sdks-tests.yml
Labels: maintenance, github actions

#3836 Remove trailing whitespace in snapshots
  milli/src/index.rs
  milli/src/snapshot_tests.rs
  milli/src/snapshots/index.rs/initial_field_distribution/1/field_distribution.snap
  milli/src/snapshots/index.rs/initial_field_distribution/field_distribution.snap
Labels: maintenance, skip changelog

#3670 Fix addition deletion bug
  .github/workflows/fuzzer-indexing.yml
  Cargo.lock
  Cargo.toml
  fuzzers/Cargo.toml
  fuzzers/README.md
  fuzzers/src/bin/fuzz-indexing.rs
  fuzzers/src/lib.rs
  index-scheduler/src/autobatcher.rs
  index-scheduler/src/lib.rs
  index-scheduler/src/snapshots/lib.rs/document_addition_and_document_deletion/after_processing_the_batch.snap
  index-scheduler/src/snapshots/lib.rs/document_addition_and_document_deletion/documents.snap
  index-scheduler/src/snapshots/lib.rs/document_addition_and_document_deletion/registered_the_first_task.snap
  index-scheduler/src/snapshots/lib.rs/document_addition_and_document_deletion/registered_the_second_task.snap
  index-scheduler/src/snapshots/lib.rs/document_deletion_and_document_addition/after_failing_the_deletion.snap
  index-scheduler/src/snapshots/lib.rs/document_deletion_and_document_addition/after_last_successful_addition.snap
  index-scheduler/src/snapshots/lib.rs/document_deletion_and_document_addition/documents.snap
  index-scheduler/src/snapshots/lib.rs/document_deletion_and_document_addition/registered_the_first_task.snap
  index-scheduler/src/snapshots/lib.rs/document_deletion_and_document_addition/registered_the_second_task.snap
  milli/Cargo.toml
  milli/src/documents/mod.rs
  milli/src/external_documents_ids.rs
  milli/src/update/delete_documents.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/transform.rs
Labels: enhancement

#3850 Experimental features
  dump/src/lib.rs
  dump/src/reader/compat/v5_to_v6.rs
  dump/src/reader/mod.rs
  dump/src/reader/v6/mod.rs
  dump/src/writer.rs
  index-scheduler/src/batch.rs
  index-scheduler/src/error.rs
  index-scheduler/src/features.rs
  index-scheduler/src/insta_snapshot.rs
  index-scheduler/src/lib.rs
  meilisearch-types/src/error.rs
  meilisearch-types/src/features.rs
  meilisearch-types/src/keys.rs
  meilisearch-types/src/lib.rs
  meilisearch/src/lib.rs
  meilisearch/src/option.rs
  meilisearch/src/routes/features.rs
  meilisearch/src/routes/indexes/search.rs
  meilisearch/src/routes/metrics.rs
  meilisearch/src/routes/mod.rs
  meilisearch/src/routes/multi_search.rs
  meilisearch/src/search.rs
  meilisearch/tests/auth/api_keys.rs
  meilisearch/tests/auth/errors.rs
Labels: experimental feature

#3825 Accept semantic vectors and allow users to query nearest neighbors
  Cargo.lock
  index-scheduler/src/features.rs
  meilisearch-types/src/error.rs
  meilisearch/Cargo.toml
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/routes/indexes/search.rs
  meilisearch/src/search.rs
  milli/Cargo.toml
  milli/examples/search.rs
  milli/src/distance.rs
  milli/src/error.rs
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/readable_slices.rs
  milli/src/search/mod.rs
  milli/src/search/new/matches/mod.rs
  milli/src/search/new/mod.rs
  milli/src/update/clear_documents.rs
  milli/src/update/delete_documents.rs
  milli/src/update/index_documents/extract/extract_vector_points.rs
  milli/src/update/index_documents/extract/mod.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/typed_chunk.rs
Labels: experimental feature

#3855 Change and add links to the Cloud
  README.md
Labels: skip changelog

#3859 Merge all analytics events pertaining to updating the experimental features
  meilisearch/src/routes/features.rs
Labels: skip changelog

#3745 tests: add unit test for `PayloadTooLarge` error
  meilisearch/src/extractors/payload.rs
Labels: maintenance

#3861 Add "meilisearch" prefix to last metrics that were missing it
  assets/grafana-dashboard.json
  meilisearch/src/metrics.rs
Labels: experimental feature

#3864 Remove `/experimental-features` verbs that weren't in the PRD
  meilisearch/src/routes/features.rs
Labels: impacts docs
