Repository meilisearch/meilisearch, pull requests merged in 2023-01, with the labels that each got.

#3274 Reject master keys that are less than 16 bytes and add `--generate-master-key` CLI option
  Cargo.lock
  meilisearch-auth/Cargo.toml
  meilisearch-auth/src/lib.rs
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/main.rs
  meilisearch/src/option.rs
Labels: breaking change

#3296 Remove `--disable-auto-batching` CLI option
  config.toml
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/lib.rs
  meilisearch/src/option.rs
Labels: breaking change

#3281 Merge `--schedule-snapshot` and `--snapshot-interval-sec` options
  config.toml
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/lib.rs
  meilisearch/src/option.rs
  meilisearch/tests/snapshot/mod.rs
Labels: breaking change, missing spec

#3269 Simplify primary key inference
  Cargo.lock
  dump/src/reader/compat/v5_to_v6.rs
  dump/src/reader/mod.rs
  meilisearch-types/Cargo.toml
  meilisearch-types/src/error.rs
  meilisearch/Cargo.toml
  meilisearch/src/main.rs
  meilisearch/tests/documents/add_documents.rs
Labels: milli, breaking change

#3278 Remove `--max-index-size` and `--max-task-db-size` flags
  config.toml
  index-scheduler/src/lib.rs
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/option.rs
Labels: breaking change

#3251 Add a specific test on finite pagination placeolder search with disti…
  meilisearch/tests/search/pagination.rs
Labels: skip changelog

#3266 Improve the way we receive the documents payload- serde multiple ndjson fix
  meilisearch-types/src/document_formats.rs
  meilisearch/tests/assets/test_set.ndjson
  meilisearch/tests/common/index.rs
  meilisearch/tests/common/service.rs
  meilisearch/tests/documents/add_documents.rs
Labels: bug

#3302 Update insta snap tests for index dates of dump v5
  dump/src/reader/mod.rs
  dump/src/reader/v5/mod.rs
Labels: maintenance

#3305 Remove hidden but usable CLI arguments
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/option.rs
Labels: breaking change

#3246 Implement most of the error handling enhancement planned for v1.0
  Cargo.lock
  dump/src/lib.rs
  dump/src/reader/compat/v5_to_v6.rs
  dump/src/reader/v6/mod.rs
  index-scheduler/src/batch.rs
  index-scheduler/src/error.rs
  index-scheduler/src/snapshots/lib.rs/swap_indexes_errors/first_swap_failed.snap
  meilisearch-types/Cargo.toml
  meilisearch-types/src/error.rs
  meilisearch-types/src/keys.rs
  meilisearch-types/src/settings.rs
  meilisearch/Cargo.toml
  meilisearch/src/error.rs
  meilisearch/src/extractors/json.rs
  meilisearch/src/extractors/mod.rs
  meilisearch/src/extractors/query_parameters.rs
  meilisearch/src/routes/api_key.rs
  meilisearch/src/routes/indexes/documents.rs
  meilisearch/src/routes/indexes/mod.rs
  meilisearch/src/routes/indexes/search.rs
  meilisearch/src/routes/indexes/settings.rs
  meilisearch/src/routes/mod.rs
  meilisearch/src/routes/swap_indexes.rs
  meilisearch/src/routes/tasks.rs
  meilisearch/src/search.rs
  meilisearch/tests/auth/api_keys.rs
  meilisearch/tests/search/errors.rs
  meilisearch/tests/tasks/mod.rs
Labels: error handler

#3317 Remove the unused error codes
  dump/src/reader/compat/v5_to_v6.rs
  meilisearch-types/src/error.rs
  meilisearch/src/error.rs
  meilisearch/tests/search/errors.rs
  meilisearch/tests/settings/get_settings.rs
  meilisearch/tests/tasks/mod.rs
Labels: error handler

#3322 Update mini-dashboard to v0.2.5
  meilisearch/Cargo.toml
Labels: tooling

#3328 Replace published by released
  .github/workflows/latest-git-tag.yml
  .github/workflows/publish-deb-brew-pkg.yml
Labels: bug, maintenance, github actions

#3326 Test error codes on settings
  meilisearch/tests/settings/errors.rs
  meilisearch/tests/settings/mod.rs
Labels: maintenance, error handler

#3321 Update the system http error code to return an internal server error
  meilisearch-types/src/error.rs
Labels: error handler

#3330 test the error codes on the task routes + fix the missing error codes on the limit and from
  meilisearch-types/Cargo.toml
  meilisearch/Cargo.toml
  meilisearch/src/analytics/mock_analytics.rs
  meilisearch/src/analytics/mod.rs
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/routes/tasks.rs
  meilisearch/tests/search/mod.rs
  meilisearch/tests/tasks/errors.rs
  meilisearch/tests/tasks/mod.rs
Labels: bug, maintenance, error handler

#3339 Continued deserr integration
  Cargo.lock
  dump/src/reader/v4/errors.rs
  dump/src/reader/v5/errors.rs
  meilisearch-auth/src/lib.rs
  meilisearch-auth/src/store.rs
  meilisearch-types/Cargo.toml
  meilisearch-types/src/deserr/error_messages.rs
  meilisearch-types/src/deserr/mod.rs
  meilisearch-types/src/deserr/query_params.rs
  meilisearch-types/src/error.rs
  meilisearch-types/src/index_uid.rs
  meilisearch-types/src/keys.rs
  meilisearch-types/src/lib.rs
  meilisearch-types/src/settings.rs
  meilisearch-types/src/star_or.rs
  meilisearch-types/src/tasks.rs
  meilisearch/Cargo.toml
  meilisearch/src/error.rs
  meilisearch/src/routes/api_key.rs
  meilisearch/src/routes/indexes/documents.rs
  meilisearch/src/routes/indexes/mod.rs
  meilisearch/src/routes/indexes/search.rs
  meilisearch/src/routes/indexes/settings.rs
  meilisearch/src/routes/mod.rs
  meilisearch/src/routes/swap_indexes.rs
  meilisearch/src/routes/tasks.rs
  meilisearch/src/search.rs
  meilisearch/tests/auth/api_keys.rs
  meilisearch/tests/common/index.rs
  meilisearch/tests/common/server.rs
  meilisearch/tests/index/create_index.rs
  meilisearch/tests/index/get_index.rs
  meilisearch/tests/search/errors.rs
  meilisearch/tests/settings/errors.rs
  meilisearch/tests/settings/get_settings.rs
  meilisearch/tests/tasks/errors.rs
  meilisearch/tests/tasks/mod.rs
Labels: breaking change, error handler

#3355 fix the wrong error code on minWordSizeForTypos
  dump/src/reader/compat/v5_to_v6.rs
  meilisearch-types/src/error.rs
  meilisearch-types/src/settings.rs
  meilisearch/tests/settings/errors.rs
Labels: bug, error handler

#3348 fix cargo flaky
  .github/workflows/flaky.yml
Labels: bug, maintenance

#3341 add functionnal + error tests on the swap_indexes route and fix a confusing error message
  meilisearch/src/error.rs
  meilisearch/tests/integration.rs
  meilisearch/tests/swap_indexes/errors.rs
  meilisearch/tests/swap_indexes/mod.rs
Labels: maintenance

#3383 Fix api key patch
  meilisearch-auth/src/lib.rs
  meilisearch-types/src/keys.rs
  meilisearch/tests/auth/api_keys.rs
Labels: bug

#3393 improve the error message when no task filter are specified for the cancelation or deletion of tasks
  index-scheduler/src/error.rs
  meilisearch/tests/tasks/mod.rs
Labels: error handler

#3398 Error links use underscores again
  dump/src/reader/compat/v5_to_v6.rs
  dump/src/reader/mod.rs
  index-scheduler/src/snapshots/lib.rs/swap_indexes_errors/first_swap_failed.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_cant_create_index_without_index/after_processing_the_10_tasks.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_cant_create_index_without_index_without_autobatching/all_tasks_processed.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_cant_create_index_without_index_without_autobatching/five_tasks_processed.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_mixed_right_without_index_starts_with_cant_create/all_tasks_processed.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_mixed_right_without_index_starts_with_cant_create/only_first_task_failed.snap
  meilisearch-types/src/error.rs
  meilisearch/src/routes/tasks.rs
  meilisearch/tests/auth/api_keys.rs
  meilisearch/tests/auth/authorization.rs
  meilisearch/tests/auth/payload.rs
  meilisearch/tests/auth/tenant_token.rs
  meilisearch/tests/content_type.rs
  meilisearch/tests/documents/add_documents.rs
  meilisearch/tests/documents/delete_documents.rs
  meilisearch/tests/documents/errors.rs
  meilisearch/tests/documents/get_documents.rs
  meilisearch/tests/documents/update_documents.rs
  meilisearch/tests/index/create_index.rs
  meilisearch/tests/index/delete_index.rs
  meilisearch/tests/index/get_index.rs
  meilisearch/tests/index/stats.rs
  meilisearch/tests/index/update_index.rs
  meilisearch/tests/search/errors.rs
  meilisearch/tests/settings/errors.rs
  meilisearch/tests/settings/get_settings.rs
  meilisearch/tests/swap_indexes/errors.rs
  meilisearch/tests/tasks/errors.rs
  meilisearch/tests/tasks/mod.rs
Labels: impacts docs

#3401 improve the error messages for the immutable fields
  meilisearch-types/src/deserr/error_messages.rs
  meilisearch-types/src/keys.rs
  meilisearch/src/routes/indexes/mod.rs
  meilisearch/tests/auth/api_keys.rs
Labels: enhancement, error handler

#3343 Extract creation and last updated timestamp for v3 dump
  dump/src/reader/v3/mod.rs
  dump/src/reader/v3/updates.rs
Labels: enhancement

#3395 Indicate filterable attributes in facet distributions when user requests a non filterable one.
  Cargo.lock
  meilisearch-types/Cargo.toml
  meilisearch/Cargo.toml
  meilisearch/tests/search/errors.rs
Labels: milli

#3404 Fix matching strategy error
  meilisearch/tests/search/errors.rs
Labels: bug

#3396 Update our error message about negative integer
  meilisearch-types/src/deserr/error_messages.rs
Labels: milli, error handler

#3387 Update create-issue-dependencies.yml
  .github/workflows/create-issue-dependencies.yml
Labels: documentation, skip changelog

#3416 Add tests on the index resource
  meilisearch/tests/common/index.rs
  meilisearch/tests/common/server.rs
  meilisearch/tests/index/errors.rs
  meilisearch/tests/index/mod.rs
Labels: maintenance, skip changelog, error handler

#3412 When adding documents, trying to update the primary-key now throw an error
  index-scheduler/src/autobatcher.rs
  index-scheduler/src/batch.rs
  index-scheduler/src/lib.rs
  index-scheduler/src/snapshots/lib.rs/test_document_addition_cant_create_index_with_index/documents.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_cant_create_index_with_index_without_autobatching/documents.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_mixed_right_without_index_starts_with_cant_create/documents.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_mixed_rights_with_index/documents.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_bad_primary_key/after_registering_the_5_tasks.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_bad_primary_key/documents.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_bad_primary_key/fifth_task_succeeds.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_bad_primary_key/first_and_second_task_fails.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_bad_primary_key/fourth_task_fails.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_bad_primary_key/third_task_succeeds.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_multiple_primary_key/after_registering_the_3_tasks.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_multiple_primary_key/documents.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_multiple_primary_key/only_first_task_succeed.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_multiple_primary_key/second_task_fails.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_multiple_primary_key/third_task_fails.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_multiple_primary_key_batch_wrong_key/after_registering_the_3_tasks.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_multiple_primary_key_batch_wrong_key/documents.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_multiple_primary_key_batch_wrong_key/only_first_task_succeed.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_multiple_primary_key_batch_wrong_key/second_and_third_tasks_fails.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_set_and_null_primary_key/after_registering_the_6_tasks.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_set_and_null_primary_key/all_other_tasks_succeeds.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_set_and_null_primary_key/documents.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_set_and_null_primary_key/first_task_fails.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_set_and_null_primary_key/second_task_fails.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_set_and_null_primary_key/third_task_succeeds.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_set_and_null_primary_key_inference_works/after_registering_the_6_tasks.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_set_and_null_primary_key_inference_works/all_other_tasks_succeeds.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_set_and_null_primary_key_inference_works/documents.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_set_and_null_primary_key_inference_works/first_task_succeed.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_set_and_null_primary_key_inference_works/second_task_fails.snap
  index-scheduler/src/snapshots/lib.rs/test_document_addition_with_set_and_null_primary_key_inference_works/third_task_succeeds.snap
  index-scheduler/src/snapshots/lib.rs/test_document_replace/documents.snap
  index-scheduler/src/snapshots/lib.rs/test_document_replace_without_autobatching/documents.snap
  index-scheduler/src/snapshots/lib.rs/test_document_update/documents.snap
  index-scheduler/src/snapshots/lib.rs/test_document_update_without_autobatching/documents.snap
  index-scheduler/src/snapshots/lib.rs/test_mixed_document_addition/documents.snap
  index-scheduler/src/utils.rs
  meilisearch/tests/documents/add_documents.rs
Labels: bug, breaking change, error handler

#3418 Compute the size of the auth-controller, index-scheduler and all update files in the global stats
  file-store/src/lib.rs
  index-scheduler/src/insta_snapshot.rs
  index-scheduler/src/lib.rs
  index-scheduler/src/utils.rs
  meilisearch-auth/src/lib.rs
  meilisearch-auth/src/store.rs
  meilisearch-types/src/error.rs
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/main.rs
  meilisearch/src/routes/mod.rs
Labels: bug

#3415 Test all the errors of wrong `_geo` field and bump milli
  Cargo.lock
  meilisearch-types/Cargo.toml
  meilisearch/tests/documents/add_documents.rs
Labels: milli, breaking change

#3434 Make clippy happy for Rust 1.67, allow `uninlined_format_args`
  .github/workflows/rust.yml
  dump/src/lib.rs
  dump/src/reader/v5/mod.rs
  index-scheduler/src/batch.rs
  meilisearch/src/search.rs
  milli/src/index.rs
  milli/src/search/criteria/proximity.rs
  milli/src/search/criteria/typo.rs
  milli/src/update/delete_documents.rs
  milli/src/update/facet/incremental.rs
  milli/src/update/index_documents/helpers/grenad_helpers.rs
  milli/src/update/index_documents/transform.rs
Labels: maintenance, skip changelog

#3437 Make clippy happy for Rust 1.67, allow uninlined_format_args
  .github/workflows/rust.yml
  dump/src/lib.rs
  dump/src/reader/v5/mod.rs
  index-scheduler/src/batch.rs
  meilisearch/src/search.rs
  permissive-json-pointer/src/lib.rs
Labels: maintenance, skip changelog

#3433 Add prototype guide to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#3439 Add git config about ownership in Docker CI
  .github/workflows/publish-docker-images.yml
Labels: bug, maintenance, github actions
