Repository meilisearch/meilisearch, pull requests merged in 2023-10, with the labels that each got.

#4082 Update sprint_issue.md
  .github/ISSUE_TEMPLATE/sprint_issue.md
Labels: documentation

#4125 Rename benchmark CI file to find it easily in the manifest list
  .github/workflows/benchmarks-pr.yml
Labels: skip changelog

#4073 Simplify Puffin report exports
  Cargo.lock
  PROFILING.md
  index-scheduler/src/batch.rs
  index-scheduler/src/features.rs
  index-scheduler/src/insta_snapshot.rs
  index-scheduler/src/lib.rs
  meilisearch-types/src/features.rs
  meilisearch/Cargo.toml
  meilisearch/src/main.rs
  meilisearch/src/routes/features.rs
  meilisearch/tests/features/mod.rs
  milli/src/update/delete_documents.rs
Labels: enhancement, experimental feature

#4136 Diff Indexing on the facet values extractors
  milli/src/heed_codec/roaring_bitmap/cbo_roaring_bitmap_codec.rs
  milli/src/update/facet/bulk.rs
  milli/src/update/facet/mod.rs
  milli/src/update/index_documents/extract/extract_facet_number_docids.rs
  milli/src/update/index_documents/extract/extract_facet_string_docids.rs
  milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs
  milli/src/update/index_documents/extract/mod.rs
  milli/src/update/index_documents/helpers/merge_functions.rs
  milli/src/update/index_documents/helpers/mod.rs
Labels: indexing

#4174 Fix warnings
  meilisearch/tests/common/mod.rs
  milli/src/search/facet/filter.rs
  milli/src/search/mod.rs
  milli/src/search/new/ranking_rule_graph/mod.rs
  milli/src/update/index_documents/helpers/mod.rs
  milli/src/update/index_documents/mod.rs
Labels: maintenance

#4167 Introduce the `meilitool` command line interface
  Cargo.lock
  Cargo.toml
  Dockerfile
  index-scheduler/src/lib.rs
  meilitool/Cargo.toml
  meilitool/src/main.rs
  meilitool/src/uuid_codec.rs
Labels: maintenance
