Repository meilisearch/meilisearch, pull requests merged in 2023-05, with the labels that each got.

#3709 Add SDKs test in a CI
  .github/workflows/sdks-tests.yml
Labels: maintenance, github actions

#3721 Use new bors URL of our self hosted bors instance
  README.md
Labels: documentation, maintenance

#3693 Implement the auto deletion of tasks
  index-scheduler/src/insta_snapshot.rs
  index-scheduler/src/lib.rs
  index-scheduler/src/snapshots/lib.rs/test_auto_deletion_of_tasks/after_the_second_task_deletion.snap
  index-scheduler/src/snapshots/lib.rs/test_auto_deletion_of_tasks/everything_has_been_processed.snap
  index-scheduler/src/snapshots/lib.rs/test_auto_deletion_of_tasks/task_deletion_have_been_enqueued.snap
  index-scheduler/src/snapshots/lib.rs/test_auto_deletion_of_tasks/task_deletion_have_been_processed.snap
  index-scheduler/src/snapshots/lib.rs/test_auto_deletion_of_tasks/task_queue_is_full.snap
  meilisearch/src/lib.rs
  meilisearch/tests/tasks/mod.rs
Labels: bug

#3726 Fix prefix highlighting
  milli/src/search/new/matches/matching_words.rs
  milli/src/search/new/matches/mod.rs
  milli/src/search/new/query_term/mod.rs
Labels: bug

#3731 Move comments above keys in config.toml
  config.toml
Labels: documentation

#3742 Compute split words derivations of terms that don't accept typos
  milli/src/search/new/query_term/compute_derivations.rs
  milli/src/search/new/tests/ngram_split_words.rs
  milli/src/search/new/tests/typo.rs
Labels: bug, search relevancy

#3739 fix: update `payload_too_large` error message to include human readable maximum acceptable payload size
  meilisearch/src/error.rs
  meilisearch/src/extractors/payload.rs
  meilisearch/tests/documents/add_documents.rs
Labels: missing spec

#3651 Use the writemap flag to reduce the memory usage
  Cargo.lock
  config.toml
  index-scheduler/src/index_mapper/index_map.rs
  index-scheduler/src/index_mapper/mod.rs
  index-scheduler/src/lib.rs
  meilisearch-auth/src/store.rs
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/lib.rs
  meilisearch/src/main.rs
  meilisearch/src/option.rs
  milli/Cargo.toml
  milli/src/index.rs
  milli/src/update/facet/mod.rs
Labels: experimental feature

#3749 Fix back: sort error message
  meilisearch/tests/search/errors.rs
  milli/src/error.rs
Labels: bug

#3741 Add ngram support to the highlighter
  milli/src/search/new/mod.rs
  milli/src/search/new/query_graph.rs
Labels: bug

#3755 Re-add final dot
  meilisearch/tests/search/errors.rs
  milli/src/error.rs
Labels: bug

#3759 Invalid error code when parsing filters
  index-scheduler/src/batch.rs
  index-scheduler/src/error.rs
  meilisearch/src/routes/indexes/documents.rs
  meilisearch/tests/auth/authorization.rs
  meilisearch/tests/documents/errors.rs
Labels: bug, error handler

#3775 Last error code changes on the new get/delete documents routes
  meilisearch-types/src/deserr/mod.rs
  meilisearch-types/src/error.rs
  meilisearch/src/error.rs
  meilisearch/src/routes/indexes/documents.rs
  meilisearch/src/routes/tasks.rs
  meilisearch/tests/documents/errors.rs
  meilisearch/tests/tasks/mod.rs
Labels: error handler

#3779 Add a cron test with disabled tokenization (with @roy9495)
  .github/workflows/test-suite.yml
Labels: maintenance

#3781 Revert "Improve docker cache"
  .dockerignore
  .github/workflows/publish-docker-images.yml
  Dockerfile
Labels: maintenance

#3792 fix the type of the document deletion by filter tasks
  index-scheduler/src/utils.rs
  meilisearch-types/src/tasks.rs
  meilisearch/src/routes/tasks.rs
  meilisearch/tests/tasks/errors.rs
Labels: bug, error handler

#3783 Improve SDK CI to choose the Docker image
  .github/workflows/sdks-tests.yml
Labels: maintenance
