Repository meilisearch/meilisearch, pull requests merged in 2023-07, with the labels that each got.

#3873 Format let-else ❤️ 🎉
  index-scheduler/src/index_mapper/index_map.rs
  meilisearch-types/src/keys.rs
  milli/src/score_details.rs
  milli/src/search/new/bucket_sort.rs
  milli/src/search/new/graph_based_ranking_rule.rs
  milli/src/search/new/matches/matching_words.rs
  milli/src/search/new/query_graph.rs
  milli/src/search/new/query_term/mod.rs
  milli/src/search/new/ranking_rule_graph/proximity/build.rs
  milli/src/search/new/sort.rs
  milli/src/update/index_documents/mod.rs
Labels: maintenance

#3876 Fix invalid attributeToSearchOn error code
  meilisearch-types/src/error.rs
  meilisearch/src/routes/indexes/facet_search.rs
  meilisearch/src/routes/indexes/search.rs
  meilisearch/src/search.rs
  meilisearch/tests/search/errors.rs
Labels: bug, skip changelog

#3878 Remove unsafe `atty` dependency
  Cargo.lock
  benchmarks/Cargo.toml
  flatten-serde-json/Cargo.toml
  json-depth-checker/Cargo.toml
  meilisearch/Cargo.toml
  meilisearch/src/main.rs
  milli/Cargo.toml
Labels: security

#3906 Add "scoring.*" analytics to multi search route
  meilisearch/src/analytics/segment_analytics.rs
Labels: skip changelog

#3904 Sort by lexicographic order after normalization
  milli/src/update/settings.rs
Labels: bug

#3908 Allow a comma-separated value to the `vector` argument in GET search
  meilisearch/src/routes/indexes/search.rs
Labels: skip changelog

#3901 Fix experimental analytics
  meilisearch/src/routes/features.rs
Labels: skip changelog, experimental feature

#3913 Expose a Puffin server to profile the indexing process
  Cargo.lock
  PROFILING.md
  assets/profiling-example.png
  index-scheduler/Cargo.toml
  index-scheduler/src/batch.rs
  index-scheduler/src/lib.rs
  meilisearch/Cargo.toml
  meilisearch/src/main.rs
  milli/Cargo.toml
  milli/src/update/clear_documents.rs
  milli/src/update/delete_documents.rs
  milli/src/update/index_documents/enrich.rs
  milli/src/update/index_documents/extract/extract_docid_word_positions.rs
  milli/src/update/index_documents/extract/extract_facet_number_docids.rs
  milli/src/update/index_documents/extract/extract_facet_string_docids.rs
  milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs
  milli/src/update/index_documents/extract/extract_fid_word_count_docids.rs
  milli/src/update/index_documents/extract/extract_geo_points.rs
  milli/src/update/index_documents/extract/extract_vector_points.rs
  milli/src/update/index_documents/extract/extract_word_docids.rs
  milli/src/update/index_documents/extract/extract_word_fid_docids.rs
  milli/src/update/index_documents/extract/extract_word_pair_proximity_docids.rs
  milli/src/update/index_documents/extract/extract_word_position_docids.rs
  milli/src/update/index_documents/extract/mod.rs
  milli/src/update/index_documents/helpers/grenad_helpers.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/transform.rs
  milli/src/update/index_documents/typed_chunk.rs
  milli/src/update/prefix_word_pairs/mod.rs
  milli/src/update/prefix_word_pairs/prefix_word.rs
  milli/src/update/prefix_word_pairs/word_prefix.rs
  milli/src/update/settings.rs
  milli/src/update/word_prefix_docids.rs
  milli/src/update/words_prefix_integer_docids.rs
  milli/src/update/words_prefixes_fst.rs
Labels: performance, tooling, maintenance, indexing

#3937 Update Charabia to the last version
  Cargo.lock
  milli/Cargo.toml
Labels: bug

#3949 Fix score details casing
  meilisearch/tests/search/mod.rs
  milli/src/score_details.rs
Labels: bug

#3952 Use the new safe `read-txn-no-tls` heed feature
  Cargo.lock
  milli/Cargo.toml
Labels: security

#3955 Update mini-dashboard to version 0.2.11
  meilisearch/Cargo.toml
Labels: tooling

#3963 Fix the milli crate
  milli/Cargo.toml
Labels: maintenance
