Repository meilisearch/meilisearch, pull requests merged in 2023-11, with the labels that each got.

#4191 Remove banner
  README.md
Labels: documentation

#4204 Throw error when the vector search is sent with the wrong size
  milli/src/search/new/mod.rs
Labels: bug

#4205 Prevent search hang on the processing index
  index-scheduler/src/batch.rs
  index-scheduler/src/insta_snapshot.rs
  index-scheduler/src/lib.rs
Labels: bug, performance

#4208 Makes the dump cancellable
  index-scheduler/src/batch.rs
  index-scheduler/src/error.rs
  index-scheduler/src/lib.rs
  index-scheduler/src/snapshots/lib.rs/cancel_processing_dump/after_dump_register.snap
  index-scheduler/src/snapshots/lib.rs/cancel_processing_dump/cancel_processed.snap
  index-scheduler/src/snapshots/lib.rs/cancel_processing_dump/cancel_registered.snap
Labels: bug

#4234 Fix puffin in the index scheduler
  index-scheduler/Cargo.toml
Labels: maintenance
