Repository meilisearch/meilisearch, pull requests merged in 2023-04, with the labels that each got.

#3636 Add a newline after the meilisearch version in the issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, skip changelog

#3643 Add sprint issue to the template issues
  .github/ISSUE_TEMPLATE/sprint_issue.md
Labels: documentation

#3649 Update the prototype section in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, skip changelog

#3666 Update README to reference new docs website
  README.md
Labels: documentation

#3694 Remove Uffizzi because not used by the team
  .github/uffizzi/Dockerfile
  .github/uffizzi/docker-compose.uffizzi.yml
  .github/uffizzi/nginx/nginx.conf
  .github/workflows/uffizzi-build.yml
  .github/workflows/uffizzi-preview-deploy.yml
Labels: maintenance

#3695 Update clippy toolchain from v1.67 to v1.69
  .github/workflows/test-suite.yml
  dump/src/reader/compat/v2_to_v3.rs
  meilisearch/tests/documents/add_documents.rs
  milli/src/search/criteria/exactness.rs
  milli/src/search/facet/facet_distribution.rs
  milli/src/search/facet/facet_distribution_iter.rs
  milli/src/search/facet/facet_range_search.rs
  milli/src/search/facet/facet_sort_ascending.rs
  milli/src/search/facet/facet_sort_descending.rs
  milli/src/search/query_tree.rs
  milli/src/update/facet/incremental.rs
  milli/src/update/index_documents/mod.rs
Labels: maintenance

#3696 Remove the unused snapshot files
  index-scheduler/src/snapshots/lib.rs/document_addition_and_document_deletion/after_processing_the_batch.snap
  index-scheduler/src/snapshots/lib.rs/document_addition_and_document_deletion/documents.snap
  index-scheduler/src/snapshots/lib.rs/document_addition_and_document_deletion/registered_the_first_task.snap
  index-scheduler/src/snapshots/lib.rs/document_addition_and_document_deletion/registered_the_second_task.snap
  index-scheduler/src/snapshots/lib.rs/document_deletion_and_document_addition/after_failing_the_deletion.snap
  index-scheduler/src/snapshots/lib.rs/document_deletion_and_document_addition/after_last_successful_addition.snap
  index-scheduler/src/snapshots/lib.rs/document_deletion_and_document_addition/documents.snap
  index-scheduler/src/snapshots/lib.rs/document_deletion_and_document_addition/registered_the_first_task.snap
  index-scheduler/src/snapshots/lib.rs/document_deletion_and_document_addition/registered_the_second_task.snap
Labels: maintenance

#3464 Remove CLI changes for clippy
  .github/workflows/test-suite.yml
Labels: maintenance
