Repository meilisearch/meilisearch, pull requests merged in 2023-12, with the labels that each got.

#4257 Change proximity precision settings
  index-scheduler/src/batch.rs
  index-scheduler/src/features.rs
  meilisearch-types/src/features.rs
  meilisearch-types/src/settings.rs
  meilisearch/src/routes/features.rs
  meilisearch/src/routes/indexes/settings.rs
  meilisearch/tests/assets/v6_v1.6.0_use_deactivated_experimental_setting.dump
  meilisearch/tests/dumps/mod.rs
  meilisearch/tests/features/mod.rs
  meilisearch/tests/search/hybrid.rs
  meilisearch/tests/settings/proximity_settings.rs
  milli/src/proximity.rs
  milli/src/search/new/db_cache.rs
  milli/src/update/index_documents/extract/mod.rs
Labels: skip changelog

#4268 Add libstdc++ in Dockerfile
  Dockerfile
Labels: bug

#4277 Update mini-dashboard to v0.2.12
  meilisearch/Cargo.toml
Labels: tooling

#4238 Task queue webhook
  Cargo.lock
  index-scheduler/Cargo.toml
  index-scheduler/src/insta_snapshot.rs
  index-scheduler/src/lib.rs
  meilisearch-types/src/lib.rs
  meilisearch-types/src/task_view.rs
  meilisearch/Cargo.toml
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/lib.rs
  meilisearch/src/option.rs
  meilisearch/src/routes/tasks.rs
  meilisearch/tests/tasks/mod.rs
  meilisearch/tests/tasks/webhook.rs
Labels: enhancement, prototype available

#4279 Check experimental feature on setting update query rather than in the task.
  index-scheduler/src/batch.rs
  meilisearch/src/routes/indexes/settings.rs
Labels: skip changelog
