Repository meilisearch/meilisearch, pull requests merged in 2024-10, with the labels that each got.

#4971 update arroy
  Cargo.lock
  index-scheduler/Cargo.toml
  milli/Cargo.toml
  milli/src/error.rs
  milli/src/update/index_documents/mod.rs
  milli/src/vector/mod.rs
Labels: enhancement, maintenance, indexing

#4963 test: improve performance of delete_index.rs
  meilisearch/tests/common/index.rs
  meilisearch/tests/index/delete_index.rs
Labels: enhancement, maintenance

#4990 Add image source label to dockerfiles
  Dockerfile
Labels: enhancement

#4962 test: improve performance of create_index.rs
  meilisearch/tests/common/server.rs
  meilisearch/tests/index/create_index.rs
Labels: enhancement, maintenance

#4992 fix the bad experimental search queue size
  meilisearch/src/option.rs
Labels: bug

#5000 Implement the experimental drop search after and nb search per core
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/main.rs
  meilisearch/src/option.rs
Labels: performance, experimental feature, rust

#5001 Do not send empty edit document by function
  meilisearch/src/analytics/segment_analytics.rs
Labels: bug, experimental feature

#5008 Display vectors when no custom vectors where ever provided
  meilisearch/src/search/mod.rs
  meilisearch/tests/search/hybrid.rs
Labels: bug

#5011 Revamp analytics
  Cargo.lock
  meilisearch/Cargo.toml
  meilisearch/src/analytics/mock_analytics.rs
  meilisearch/src/analytics/mod.rs
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/lib.rs
  meilisearch/src/main.rs
  meilisearch/src/option.rs
  meilisearch/src/routes/dump.rs
  meilisearch/src/routes/features.rs
  meilisearch/src/routes/indexes/documents.rs
  meilisearch/src/routes/indexes/facet_search.rs
  meilisearch/src/routes/indexes/mod.rs
  meilisearch/src/routes/indexes/search.rs
  meilisearch/src/routes/indexes/search_analytics.rs
  meilisearch/src/routes/indexes/settings.rs
  meilisearch/src/routes/indexes/settings_analytics.rs
  meilisearch/src/routes/indexes/similar.rs
  meilisearch/src/routes/indexes/similar_analytics.rs
  meilisearch/src/routes/mod.rs
  meilisearch/src/routes/multi_search.rs
  meilisearch/src/routes/multi_search_analytics.rs
  meilisearch/src/routes/snapshot.rs
  meilisearch/src/routes/swap_indexes.rs
  meilisearch/src/routes/tasks.rs
  meilisearch/tests/common/server.rs
  meilisearch/tests/common/service.rs
  meilisearch/tests/logs/mod.rs
Labels: maintenance
