Repository meilisearch/meilisearch, pull requests merged in 2024-09, with the labels that each got.

#4905 Do not fail the whole batch when a single document deletion by filter fails
  index-scheduler/src/batch.rs
  index-scheduler/src/lib.rs
  index-scheduler/src/snapshots/lib.rs/fail_in_process_batch_for_document_deletion/after_adding_the_documents.snap
  index-scheduler/src/snapshots/lib.rs/fail_in_process_batch_for_document_deletion/after_adding_the_settings.snap
  index-scheduler/src/snapshots/lib.rs/fail_in_process_batch_for_document_deletion/after_adding_the_settings_and_documents.snap
  index-scheduler/src/snapshots/lib.rs/fail_in_process_batch_for_document_deletion/after_removing_the_documents.snap
  index-scheduler/src/snapshots/lib.rs/fail_in_process_batch_for_document_deletion/documents_remaining_should_only_be_bork.snap
  index-scheduler/src/snapshots/lib.rs/fail_in_process_batch_for_document_deletion/registered_the_document_deletions.snap
  index-scheduler/src/snapshots/lib.rs/fail_in_process_batch_for_document_deletion/registered_the_setting_and_document_addition.snap
Labels: bug, error handler

#4929 Add facets support to federated
  meilisearch-types/src/error.rs
  meilisearch-types/src/index_uid.rs
  meilisearch/src/error.rs
  meilisearch/src/search/federated.rs
  meilisearch/src/search/mod.rs
  meilisearch/tests/search/multi.rs
  milli/src/search/facet/facet_distribution.rs
Labels: breaking change

#4938 Remove default embedder
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/error.rs
  meilisearch/src/routes/indexes/search.rs
  meilisearch/src/routes/indexes/similar.rs
  meilisearch/src/search/mod.rs
  meilisearch/tests/search/hybrid.rs
  meilisearch/tests/search/mod.rs
  meilisearch/tests/similar/errors.rs
  meilisearch/tests/similar/mod.rs
  meilisearch/tests/vector/mod.rs
  meilisearch/tests/vector/openai.rs
  meilisearch/tests/vector/settings.rs
  milli/src/vector/mod.rs
Labels: breaking change

#4945 Add swedish in default pipelines
  Cargo.lock
  meilisearch-types/Cargo.toml
  meilisearch-types/src/locales.rs
  meilisearch/Cargo.toml
  meilisearch/tests/search/locales.rs
  milli/Cargo.toml
Labels: bug, enhancement

#4943 Correct broken links in README
  README.md
Labels: documentation

#4953 Move the multi arroy index logic to the arroy wrapper
  milli/src/index.rs
  milli/src/search/new/vector_sort.rs
  milli/src/search/similar.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/transform.rs
  milli/src/update/index_documents/typed_chunk.rs
  milli/src/vector/mod.rs
Labels: maintenance

#4960 Update rhai
  Cargo.lock
  milli/Cargo.toml
Labels: bug, experimental feature
