Repository meilisearch/meilisearch, pull requests merged in 2024-12, with the labels that each got.

#5107 While spamming the batches route we could see a processing batch becoming missing and then finished, this commit ensures the batches goes from processing to finished directly
  crates/index-scheduler/src/lib.rs
  crates/meilisearch/tests/batches/mod.rs
Labels: bug

#5110 Increase margin on deletion of task
  crates/index-scheduler/src/lib.rs
Labels: maintenance

#5056 Attach index name in error message
  crates/index-scheduler/src/batch.rs
  crates/index-scheduler/src/error.rs
  crates/index-scheduler/src/index_mapper/index_map.rs
  crates/index-scheduler/src/index_mapper/mod.rs
  crates/index-scheduler/src/lib.rs
  crates/index-scheduler/src/snapshots/lib.rs/fail_in_process_batch_for_document_deletion/after_removing_the_documents.snap
  crates/meilisearch/src/error.rs
  crates/meilisearch/src/lib.rs
  crates/meilisearch/src/routes/indexes/facet_search.rs
  crates/meilisearch/src/routes/indexes/mod.rs
  crates/meilisearch/src/routes/indexes/search.rs
  crates/meilisearch/src/routes/indexes/similar.rs
  crates/meilisearch/src/routes/multi_search.rs
  crates/meilisearch/src/search/federated.rs
  crates/meilisearch/src/search/mod.rs
  crates/meilisearch/tests/documents/add_documents.rs
  crates/meilisearch/tests/documents/errors.rs
  crates/meilisearch/tests/index/update_index.rs
  crates/meilisearch/tests/search/errors.rs
  crates/meilisearch/tests/search/multi.rs
  crates/meilisearch/tests/tasks/mod.rs
  crates/meilisearch/tests/vector/binary_quantized.rs
  crates/meilisearch/tests/vector/mod.rs
  crates/meilisearch/tests/vector/openai.rs
  crates/meilisearch/tests/vector/rest.rs
Labels: enhancement, error handler

#5146 Offline upgrade v1.12
  Cargo.lock
  crates/meilitool/Cargo.toml
  crates/meilitool/src/main.rs
  crates/meilitool/src/upgrade/mod.rs
  crates/meilitool/src/upgrade/v1_12.rs
Labels: meilitool

#5144 Exactly 512 bytes docid fails
  crates/index-scheduler/src/error.rs
  crates/meilisearch-types/src/error.rs
  crates/meilisearch/tests/documents/add_documents.rs
  crates/meilisearch/tests/documents/update_documents.rs
  crates/meilisearch/tests/similar/errors.rs
  crates/milli/src/documents/primary_key.rs
  crates/milli/src/error.rs
Labels: impacts docs

#5158 Indexer edition 2024 fix facet fst
  crates/meilisearch/tests/search/facet_search.rs
  crates/milli/src/update/new/facet_search_builder.rs
Labels: bug

#5159 Fix the New Indexer Spilling
  crates/milli/src/update/new/extract/cache.rs
Labels: bug

#5134 Split Meilisearch Crate Tests in separate file
  crates/meilisearch/src/routes/indexes/mod.rs
  crates/meilisearch/src/routes/indexes/search.rs
  crates/meilisearch/src/routes/indexes/search_test.rs
Labels: maintenance

#5171 tests: split tests in separate file
  crates/meilisearch/src/search/mod.rs
  crates/meilisearch/src/search/mod_test.rs
Labels: maintenance

#5173 Remove obsolete test code
  crates/meilisearch/src/search/mod.rs
Labels: maintenance

#5175 fix the flaky batches test
  crates/meilisearch/tests/batches/mod.rs
Labels: maintenance

#5174 Split tests for option crate meilisearch in a separate test file
  crates/meilisearch/src/lib.rs
  crates/meilisearch/src/option.rs
  crates/meilisearch/src/option_test.rs
Labels: maintenance

#5135 Check all search filter attributes are filterable upfront
  crates/filter-parser/src/lib.rs
  crates/milli/src/search/facet/filter.rs
Labels: bug, error handler, filtering

#5169 Replace hardcoded string with constants
  crates/index-scheduler/src/batch.rs
  crates/meilisearch/src/option_test.rs
  crates/meilisearch/src/search/mod.rs
  crates/milli/src/asc_desc.rs
  crates/milli/src/constants.rs
  crates/milli/src/criterion.rs
  crates/milli/src/error.rs
  crates/milli/src/fieldids_weights_map.rs
  crates/milli/src/index.rs
  crates/milli/src/lib.rs
  crates/milli/src/search/facet/filter.rs
  crates/milli/src/search/new/mod.rs
  crates/milli/src/search/new/tests/geo_sort.rs
  crates/milli/src/search/new/tests/integration.rs
  crates/milli/src/update/clear_documents.rs
  crates/milli/src/update/index_documents/enrich.rs
  crates/milli/src/update/index_documents/extract/extract_vector_points.rs
  crates/milli/src/update/index_documents/mod.rs
  crates/milli/src/update/index_documents/transform.rs
  crates/milli/src/update/index_documents/typed_chunk.rs
  crates/milli/src/update/new/document.rs
  crates/milli/src/update/new/extract/documents.rs
  crates/milli/src/update/new/extract/faceted/facet_document.rs
  crates/milli/src/update/new/extract/geo/mod.rs
  crates/milli/src/update/new/vector_document.rs
  crates/milli/src/update/settings.rs
  crates/milli/src/vector/parsed_vectors.rs
Labels: maintenance

#5178 Add Prometheus metrics to measure task queue latency
  assets/grafana-dashboard.json
  crates/meilisearch/src/metrics.rs
  crates/meilisearch/src/routes/metrics.rs
Labels: maintenance, experimental feature

#5166 fix list indexes
  crates/index-scheduler/src/index_mapper/mod.rs
  crates/index-scheduler/src/lib.rs
  crates/meilisearch/src/lib.rs
  crates/meilisearch/src/routes/indexes/mod.rs
Labels: bug, enhancement, performance

#5192 Fix empty document addition
  crates/index-scheduler/src/batch.rs
  crates/index-scheduler/src/utils.rs
  crates/meilisearch/tests/documents/add_documents.rs
  crates/milli/src/update/new/indexer/document_operation.rs
Labels: bug
