Repository meilisearch/meilisearch, pull requests merged in 2024-01, with the labels that each got.

#4294 fix compilation warnings for release v1.6
  milli/src/update/index_documents/helpers/mod.rs
  milli/src/update/index_documents/mod.rs
Labels: maintenance

#4295 fix compilation warnings on main
  milli/src/update/index_documents/helpers/mod.rs
  milli/src/update/index_documents/mod.rs
Labels: maintenance

#4311 Limit the number of values returned by the facet search
  meilisearch/src/search.rs
  meilisearch/tests/search/facet_search.rs
  milli/src/search/mod.rs
Labels: bug

#4316 Autobatch the task deletions
  index-scheduler/src/batch.rs
  index-scheduler/src/lib.rs
  index-scheduler/src/snapshots/lib.rs/task_deletion_delete_same_task_twice/task_deletion_processed.snap
Labels: enhancement

#4319 Update README
  README.md
Labels: documentation

#4337 Remove panic on the geosearch
  meilisearch/tests/common/mod.rs
  meilisearch/tests/documents/add_documents.rs
  milli/src/update/index_documents/extract/extract_geo_points.rs
Labels: bug, error handler, geo search

#4330 Add job variable to grafana dashboard
  assets/grafana-dashboard.json
Labels: enhancement, experimental feature

#4364 Revert "Remove panic on the geosearch"
  meilisearch/tests/common/mod.rs
  meilisearch/tests/documents/add_documents.rs
  milli/src/update/index_documents/extract/extract_geo_points.rs
Labels: maintenance

#4366 Fix geo error message
  meilisearch/tests/common/mod.rs
  meilisearch/tests/documents/add_documents.rs
  milli/src/update/index_documents/extract/extract_geo_points.rs
Labels: bug, error handler, geo search
