Repository meilisearch/meilisearch, pull requests merged in 2024-11, with the labels that each got.

#5026 test: improve performance of update_documents.rs
  crates/meilisearch/tests/documents/update_documents.rs
Labels: maintenance

#5034 Upgrade from v1 10 to v1 11
  Cargo.lock
  crates/meilisearch/src/routes/indexes/search_analytics.rs
  crates/meilisearch/src/routes/indexes/settings.rs
  crates/meilisearch/src/routes/indexes/settings_analytics.rs
  crates/meilisearch/src/routes/indexes/similar_analytics.rs
  crates/meilisearch/src/routes/multi_search.rs
  crates/meilisearch/src/routes/multi_search_analytics.rs
  crates/meilisearch/tests/common/index.rs
  crates/meilitool/Cargo.toml
  crates/meilitool/src/main.rs
  crates/meilitool/src/upgrade/mod.rs
  crates/meilitool/src/upgrade/v1_10.rs
  crates/meilitool/src/upgrade/v1_11.rs
  crates/meilitool/src/upgrade/v1_9.rs
  crates/milli/Cargo.toml
Labels: meilitool

#5037 Fix the benchmarks
  .github/workflows/benchmarks-manual.yml
  .github/workflows/benchmarks-pr.yml
  .github/workflows/benchmarks-push-indexing.yml
  .github/workflows/benchmarks-push-search-songs.yml
  .github/workflows/benchmarks-push-search-wiki.yml
Labels: maintenance

#5044 Adds new metrics to prometheus
  crates/meilisearch/src/metrics.rs
  crates/meilisearch/src/routes/metrics.rs
  crates/meilisearch/src/search_queue.rs
Labels: experimental feature

#5051 Add timeout on read and write operations.
  milli/src/vector/rest.rs
Labels: enhancement, experimental feature, blocks vector store stabilization

#5048 Reverse the order of the task queue
  crates/index-scheduler/src/lib.rs
  crates/meilisearch-types/src/error.rs
  crates/meilisearch/src/routes/tasks.rs
  crates/meilisearch/tests/tasks/errors.rs
  crates/meilisearch/tests/tasks/mod.rs
Labels: enhancement

#5070 Improve the details and stats of the current batch processing
  crates/index-scheduler/src/insta_snapshot.rs
  crates/index-scheduler/src/snapshots/lib.rs/cancel_mix_of_tasks/aborted_indexation.snap
  crates/index-scheduler/src/snapshots/lib.rs/cancel_mix_of_tasks/processing_second_task_cancel_enqueued.snap
  crates/index-scheduler/src/snapshots/lib.rs/cancel_processing_dump/cancel_registered.snap
  crates/index-scheduler/src/snapshots/lib.rs/cancel_processing_task/aborted_indexation.snap
  crates/index-scheduler/src/snapshots/lib.rs/cancel_processing_task/cancel_task_registered.snap
  crates/index-scheduler/src/snapshots/lib.rs/cancel_processing_task/initial_task_processing.snap
  crates/index-scheduler/src/snapshots/lib.rs/document_addition/after_the_batch_creation.snap
  crates/index-scheduler/src/snapshots/lib.rs/fail_in_process_batch_for_document_addition/document_addition_batch_created.snap
  crates/index-scheduler/src/snapshots/lib.rs/fail_in_update_task_after_process_batch_success_for_document_addition/after_batch_succeeded.snap
  crates/index-scheduler/src/snapshots/lib.rs/fail_in_update_task_after_process_batch_success_for_document_addition/after_failing_to_commit.snap
  crates/index-scheduler/src/snapshots/lib.rs/insert_task_while_another_task_is_processing/after_batch_creation.snap
  crates/index-scheduler/src/snapshots/lib.rs/insert_task_while_another_task_is_processing/registered_the_second_task.snap
  crates/index-scheduler/src/snapshots/lib.rs/insert_task_while_another_task_is_processing/registered_the_third_task.snap
  crates/index-scheduler/src/snapshots/lib.rs/query_batches_simple/after-advancing-a-bit.snap
  crates/index-scheduler/src/snapshots/lib.rs/task_deletion_undeleteable/task_deletion_processing.snap
  crates/index-scheduler/src/utils.rs
  crates/meilisearch/tests/batches/mod.rs
Labels: enhancement

#5102 Update mini-dashboard to v0.2.16 version
  crates/meilisearch/Cargo.toml
Labels: tooling
