Repository meilisearch/meilisearch, pull requests merged in 2024-04, with the labels that each got.

#4546 Fix some typos in conments
  dump/src/reader/v2/updates.rs
  dump/src/writer.rs
  filter-parser/src/value.rs
  index-scheduler/src/autobatcher.rs
  milli/src/index.rs
  milli/src/update/words_prefixes_fst.rs
Labels: documentation

#4553 update h2
  Cargo.lock
Labels: enhancement

#4556 Update sprint_issue.md
  .github/ISSUE_TEMPLATE/sprint_issue.md
Labels: skip changelog

#4560 Bring back change from v1.7.5 to main
  Cargo.lock
Labels: skip changelog

#4568 Fix some typos in comments
  milli/src/search/new/matches/mod.rs
  milli/src/search/new/query_term/parse_query.rs
  milli/src/update/facet/incremental.rs
  milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs
Labels: documentation

#4504 Avoid clearing db in transform
  index-scheduler/src/lib.rs
  index-scheduler/src/snapshots/index_scheduler__tests__settings_update-2.snap
  index-scheduler/src/snapshots/index_scheduler__tests__settings_update-3.snap
  index-scheduler/src/snapshots/index_scheduler__tests__settings_update.snap
  index-scheduler/src/snapshots/lib.rs/test_settings_update/after_registering_settings_task.snap
  index-scheduler/src/snapshots/lib.rs/test_settings_update/settings_update_processed.snap
  meilisearch/tests/settings/get_settings.rs
  milli/src/index.rs
  milli/src/update/del_add.rs
  milli/src/update/index_documents/extract/extract_docid_word_positions.rs
  milli/src/update/index_documents/extract/extract_facet_number_docids.rs
  milli/src/update/index_documents/extract/extract_facet_string_docids.rs
  milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs
  milli/src/update/index_documents/extract/extract_fid_word_count_docids.rs
  milli/src/update/index_documents/extract/extract_vector_points.rs
  milli/src/update/index_documents/extract/extract_word_docids.rs
  milli/src/update/index_documents/extract/extract_word_pair_proximity_docids.rs
  milli/src/update/index_documents/extract/extract_word_position_docids.rs
  milli/src/update/index_documents/extract/mod.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/transform.rs
  milli/src/update/settings.rs
  workloads/settings-add-remove-filters.json
  workloads/settings-proximity-precision.json
  workloads/settings-remove-add-swap-searchable.json
  workloads/settings-typo.json
Labels: performance, settings diff-indexing

#4581 Always show facet numbers in alpha order in the facet distribution
  milli/src/search/facet/facet_distribution.rs
Labels: bug

#4597 Fix embeddings settings update
  milli/src/update/index_documents/extract/extract_vector_points.rs
  workloads/movies-subset-hf-embeddings.json
  workloads/settings-add-embeddings.json
Labels: bug
