Repository meilisearch/meilisearch, pull requests merged in 2024-02, with the labels that each got.

#4382 Bring back changes from `release-v1.6.1` into `main`
  Cargo.lock
  Cargo.toml
  meilisearch/Cargo.toml
  meilisearch/tests/common/mod.rs
  meilisearch/tests/documents/add_documents.rs
  meilisearch/tests/search/hybrid.rs
  milli/src/search/hybrid.rs
  milli/src/update/index_documents/extract/extract_geo_points.rs
  milli/src/update/index_documents/extract/extract_vector_points.rs
  milli/src/vector/error.rs
  milli/src/vector/hf.rs
  milli/src/vector/mod.rs
  milli/src/vector/openai.rs
Labels: maintenance, skip changelog

#4360 Fix broken links in README.md
  README.md
Labels: documentation

#4388 Cap the maximum memory of the grenad sorters
  milli/src/update/index_documents/helpers/grenad_helpers.rs
Labels: performance

#4400 Upgrade rustls to 0.21.10 and ring to 0.17
  Cargo.lock
  meilisearch-types/Cargo.toml
  meilisearch/Cargo.toml
  meilisearch/src/main.rs
  meilisearch/src/option.rs
Labels: maintenance

#4410 Implement the experimental log mode cli flag and log level updates at runtime
  Cargo.lock
  index-scheduler/src/features.rs
  meilisearch/Cargo.toml
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/lib.rs
  meilisearch/src/main.rs
  meilisearch/src/option.rs
  meilisearch/src/routes/logs.rs
  meilisearch/tests/common/server.rs
  meilisearch/tests/common/service.rs
  meilisearch/tests/logs/error.rs
  meilisearch/tests/logs/mod.rs
Labels: enhancement, experimental feature

#4416 Create automation when creating Milestone to create update-version issue
  .github/workflows/milestone-workflow.yml
Labels: maintenance

#4042 Implements the new replication parameters
  file-store/src/lib.rs
  index-scheduler/src/error.rs
  index-scheduler/src/insta_snapshot.rs
  index-scheduler/src/lib.rs
  index-scheduler/src/snapshots/lib.rs/test_disable_auto_deletion_of_tasks/task_deletion_have_not_been_enqueued.snap
  index-scheduler/src/snapshots/lib.rs/test_disable_auto_deletion_of_tasks/task_queue_is_full.snap
  meilisearch-types/src/document_formats.rs
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/extractors/sequential_extractor.rs
  meilisearch/src/lib.rs
  meilisearch/src/option.rs
  meilisearch/src/routes/dump.rs
  meilisearch/src/routes/indexes/documents.rs
  meilisearch/src/routes/indexes/mod.rs
  meilisearch/src/routes/indexes/settings.rs
  meilisearch/src/routes/mod.rs
  meilisearch/src/routes/snapshot.rs
  meilisearch/src/routes/swap_indexes.rs
  meilisearch/src/routes/tasks.rs
  meilisearch/tests/common/index.rs
  meilisearch/tests/documents/add_documents.rs
  meilisearch/tests/documents/errors.rs
  meilisearch/tests/index/create_index.rs
Labels: prototype available, high availability

#4442 Send custom task
  file-store/src/lib.rs
  index-scheduler/src/error.rs
  index-scheduler/src/insta_snapshot.rs
  index-scheduler/src/lib.rs
  index-scheduler/src/snapshots/lib.rs/test_disable_auto_deletion_of_tasks/task_deletion_have_not_been_enqueued.snap
  index-scheduler/src/snapshots/lib.rs/test_disable_auto_deletion_of_tasks/task_queue_is_full.snap
  meilisearch-types/src/document_formats.rs
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/extractors/sequential_extractor.rs
  meilisearch/src/lib.rs
  meilisearch/src/option.rs
  meilisearch/src/routes/dump.rs
  meilisearch/src/routes/indexes/documents.rs
  meilisearch/src/routes/indexes/mod.rs
  meilisearch/src/routes/indexes/settings.rs
  meilisearch/src/routes/mod.rs
  meilisearch/src/routes/snapshot.rs
  meilisearch/src/routes/swap_indexes.rs
  meilisearch/src/routes/tasks.rs
  meilisearch/tests/common/index.rs
  meilisearch/tests/documents/add_documents.rs
  meilisearch/tests/documents/errors.rs
  meilisearch/tests/index/create_index.rs
Labels: experimental feature, high availability

#4443 Add GPU analytics
  meilisearch/src/analytics/segment_analytics.rs
  milli/src/vector/mod.rs
Labels: skip changelog

#4453 Don't test on nightly
  .github/workflows/test-suite.yml
Labels: maintenance, skip changelog
