Repository meilisearch/meilisearch, pull requests merged in 2024-03, with the labels that each got.

#4450 Add the content type in the webhook + improve the test
  index-scheduler/src/lib.rs
  meilisearch/tests/tasks/webhook.rs
Labels: enhancement

#4445 Add subcommand to run benchmarks
  .cargo/config.toml
  .github/workflows/bench-manual.yml
  .github/workflows/bench-pr.yml
  .github/workflows/bench-push-indexing.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  Dockerfile
  build-info/Cargo.toml
  build-info/build.rs
  build-info/src/lib.rs
  meilisearch/Cargo.toml
  meilisearch/build.rs
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/lib.rs
  meilisearch/src/main.rs
  meilisearch/src/routes/mod.rs
  milli/src/update/index_documents/extract/mod.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/typed_chunk.rs
  tracing-trace/src/processor/span_stats.rs
  workloads/hackernews.json
  workloads/movies-nothreads.json
  workloads/movies.json
  xtask/Cargo.toml
  xtask/src/bench/assets.rs
  xtask/src/bench/client.rs
  xtask/src/bench/command.rs
  xtask/src/bench/dashboard.rs
  xtask/src/bench/env_info.rs
  xtask/src/bench/meili_process.rs
  xtask/src/bench/mod.rs
  xtask/src/bench/workload.rs
  xtask/src/lib.rs
  xtask/src/main.rs
Labels: maintenance

#4463 Add tests when the field limit is reached
  meilisearch/tests/documents/add_documents.rs
Labels: maintenance

#4474 Update cargo version
  Cargo.lock
  Cargo.toml
Labels: maintenance

#4475 Allow running benchmarks without sending results to the dashboard
  xtask/src/bench/dashboard.rs
  xtask/src/bench/mod.rs
  xtask/src/bench/workload.rs
Labels: maintenance

#4479 Skip reindexing when modifying unknown faceted fields
  milli/src/update/settings.rs
Labels: enhancement

#4483 Workflows: Fix reason param when benches are triggered from a comment.
  .github/workflows/bench-pr.yml
Labels: maintenance

#4491 chore: remove repetitive words
  meilisearch/src/search.rs
  milli/src/search/facet/facet_range_search.rs
  milli/src/search/new/tests/typo_proximity.rs
Labels: documentation

#4499 Fix milli link in contributing doc
  CONTRIBUTING.md
Labels: documentation

#4503 Add settings diff indexing benchmarks
  workloads/settings-add-remove-filters.json
  workloads/settings-proximity-precision.json
  workloads/settings-remove-add-swap-searchable.json
  workloads/settings-typo.json
Labels: performance, skip changelog

#4477 Add documentation for benchmarks
  BENCHMARKS.md
  CONTRIBUTING.md
Labels: documentation, maintenance

#4510 Revert "Merge remote-tracking branch 'origin/main' into release-v1.7.1"
  .github/workflows/bench-pr.yml
  .github/workflows/milestone-workflow.yml
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  meilisearch-types/Cargo.toml
  meilisearch/Cargo.toml
  meilisearch/src/main.rs
  meilisearch/src/option.rs
  meilisearch/src/routes/indexes/settings.rs
  meilisearch/src/search.rs
  meilisearch/tests/documents/add_documents.rs
  meilisearch/tests/search/facet_search.rs
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/order_by_map.rs
  milli/src/search/facet/facet_range_search.rs
  milli/src/search/facet/mod.rs
  milli/src/search/facet/search.rs
  milli/src/search/mod.rs
  milli/src/search/new/tests/typo_proximity.rs
  milli/src/update/settings.rs
  milli/src/vector/error.rs
  milli/src/vector/mod.rs
  milli/src/vector/ollama.rs
  milli/src/vector/openai.rs
  milli/src/vector/settings.rs
  workloads/settings-add-remove-filters.json
  workloads/settings-proximity-precision.json
  workloads/settings-remove-add-swap-searchable.json
  workloads/settings-typo.json
  xtask/src/bench/dashboard.rs
  xtask/src/bench/mod.rs
  xtask/src/bench/workload.rs
Labels: skip changelog

#4512 Revert "Revert "Merge remote-tracking branch 'origin/main' into release-v1.7.1""
  .github/workflows/bench-pr.yml
  .github/workflows/milestone-workflow.yml
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  meilisearch-types/Cargo.toml
  meilisearch/Cargo.toml
  meilisearch/src/main.rs
  meilisearch/src/option.rs
  meilisearch/src/routes/indexes/settings.rs
  meilisearch/src/search.rs
  meilisearch/tests/documents/add_documents.rs
  meilisearch/tests/search/facet_search.rs
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/order_by_map.rs
  milli/src/search/facet/facet_range_search.rs
  milli/src/search/facet/mod.rs
  milli/src/search/facet/search.rs
  milli/src/search/mod.rs
  milli/src/search/new/tests/typo_proximity.rs
  milli/src/update/settings.rs
  milli/src/vector/error.rs
  milli/src/vector/mod.rs
  milli/src/vector/ollama.rs
  milli/src/vector/openai.rs
  milli/src/vector/settings.rs
  workloads/settings-add-remove-filters.json
  workloads/settings-proximity-precision.json
  workloads/settings-remove-add-swap-searchable.json
  workloads/settings-typo.json
  xtask/src/bench/dashboard.rs
  xtask/src/bench/mod.rs
  xtask/src/bench/workload.rs
Labels: skip changelog

#4513 Revert "Merge remote-tracking branch 'origin/main' into release-v1.7.1"
  .github/workflows/bench-pr.yml
  .github/workflows/milestone-workflow.yml
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  meilisearch-types/Cargo.toml
  meilisearch/Cargo.toml
  meilisearch/src/main.rs
  meilisearch/src/option.rs
  meilisearch/src/routes/indexes/settings.rs
  meilisearch/src/search.rs
  meilisearch/tests/documents/add_documents.rs
  meilisearch/tests/search/facet_search.rs
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/order_by_map.rs
  milli/src/search/facet/facet_range_search.rs
  milli/src/search/facet/mod.rs
  milli/src/search/facet/search.rs
  milli/src/search/mod.rs
  milli/src/search/new/tests/typo_proximity.rs
  milli/src/update/settings.rs
  milli/src/vector/error.rs
  milli/src/vector/mod.rs
  milli/src/vector/ollama.rs
  milli/src/vector/openai.rs
  milli/src/vector/settings.rs
  workloads/settings-add-remove-filters.json
  workloads/settings-proximity-precision.json
  workloads/settings-remove-add-swap-searchable.json
  workloads/settings-typo.json
  xtask/src/bench/dashboard.rs
  xtask/src/bench/mod.rs
  xtask/src/bench/workload.rs
Labels: skip changelog

#4466 Implements the search cutoff
  assets/grafana-dashboard.json
  dump/src/lib.rs
  dump/src/reader/compat/v5_to_v6.rs
  meilisearch-types/src/error.rs
  meilisearch-types/src/settings.rs
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/metrics.rs
  meilisearch/src/routes/indexes/search.rs
  meilisearch/src/routes/indexes/settings.rs
  meilisearch/src/search.rs
  meilisearch/tests/common/index.rs
  meilisearch/tests/common/mod.rs
  meilisearch/tests/dumps/mod.rs
  meilisearch/tests/search/mod.rs
  meilisearch/tests/settings/errors.rs
  meilisearch/tests/settings/get_settings.rs
  milli/examples/search.rs
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/score_details.rs
  milli/src/search/hybrid.rs
  milli/src/search/mod.rs
  milli/src/search/new/bucket_sort.rs
  milli/src/search/new/matches/mod.rs
  milli/src/search/new/mod.rs
  milli/src/search/new/tests/cutoff.rs
  milli/src/search/new/tests/mod.rs
  milli/src/update/settings.rs
Labels: performance, search relevancy

#4522 Brings back change to main
  Cargo.lock
  index-scheduler/src/lib.rs
Labels: skip changelog

#4526 Remove repetitive word in Benchmark docs
  BENCHMARKS.md
Labels: documentation

#4373 feat: add status code label to prometheus http request counter
  assets/grafana-dashboard.json
  meilisearch/src/metrics.rs
  meilisearch/src/middleware.rs
Labels: experimental feature

#4516 Update sprint_issue.md
  .github/ISSUE_TEMPLATE/sprint_issue.md
Labels: documentation

#4520 Add automation to create openAPI issue
  .github/workflows/milestone-workflow.yml
Labels: maintenance

#4542 fixes typos
  index-scheduler/src/lib.rs
Labels: enhancement

#4532 Add `url` and `api_key` to ollama
  milli/src/update/settings.rs
  milli/src/vector/mod.rs
  milli/src/vector/ollama.rs
  milli/src/vector/settings.rs
Labels: skip changelog

#4536 Limit concurrent search requests
  meilisearch-types/src/error.rs
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/error.rs
  meilisearch/src/lib.rs
  meilisearch/src/option.rs
  meilisearch/src/routes/indexes/facet_search.rs
  meilisearch/src/routes/indexes/search.rs
  meilisearch/src/routes/mod.rs
  meilisearch/src/routes/multi_search.rs
  meilisearch/src/search_queue.rs
  meilisearch/tests/search/mod.rs
  meilisearch/tests/search/search_queue.rs
Labels: CPU/RAM usage, experimental feature

#4543 Bring back changes from v1.7.4 into main
  milli/src/update/settings.rs
Labels: skip changelog
