Repository meilisearch/meilisearch, pull requests merged in 2024-05, with the labels that each got.

#4619 Use http path pattern instead of full path in metrics
  meilisearch/src/middleware.rs
  meilisearch/src/routes/mod.rs
Labels: enhancement, experimental feature

#4621 Bring back changes from v1.8.0 into main
  Cargo.lock
  dump/src/lib.rs
  dump/src/reader/compat/v5_to_v6.rs
  index-scheduler/src/lib.rs
  index-scheduler/src/snapshots/index_scheduler__tests__settings_update-2.snap
  index-scheduler/src/snapshots/index_scheduler__tests__settings_update-3.snap
  index-scheduler/src/snapshots/index_scheduler__tests__settings_update.snap
  index-scheduler/src/snapshots/lib.rs/test_settings_update/after_registering_settings_task.snap
  index-scheduler/src/snapshots/lib.rs/test_settings_update/settings_update_processed.snap
  meilisearch-types/Cargo.toml
  meilisearch-types/src/settings.rs
  meilisearch/Cargo.toml
  meilisearch/src/analytics/mock_analytics.rs
  meilisearch/src/analytics/mod.rs
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/option.rs
  meilisearch/src/routes/indexes/mod.rs
  meilisearch/src/routes/indexes/settings.rs
  meilisearch/src/routes/mod.rs
  meilisearch/src/routes/tasks.rs
  meilisearch/src/search.rs
  meilisearch/tests/settings/get_settings.rs
  milli/Cargo.toml
  milli/src/error.rs
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/search/facet/facet_distribution.rs
  milli/src/thread_pool_no_abort.rs
  milli/src/update/del_add.rs
  milli/src/update/index_documents/extract/extract_docid_word_positions.rs
  milli/src/update/index_documents/extract/extract_facet_number_docids.rs
  milli/src/update/index_documents/extract/extract_facet_string_docids.rs
  milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs
  milli/src/update/index_documents/extract/extract_fid_word_count_docids.rs
  milli/src/update/index_documents/extract/extract_vector_points.rs
  milli/src/update/index_documents/extract/extract_word_docids.rs
  milli/src/update/index_documents/extract/extract_word_pair_proximity_docids.rs
  milli/src/update/index_documents/extract/extract_word_position_docids.rs
  milli/src/update/index_documents/extract/mod.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/transform.rs
  milli/src/update/indexer_config.rs
  milli/src/update/settings.rs
  milli/src/vector/error.rs
  milli/src/vector/mod.rs
  milli/src/vector/ollama.rs
  milli/src/vector/openai.rs
  milli/src/vector/rest.rs
  milli/src/vector/settings.rs
  tracing-trace/src/processor/firefox_profiler.rs
  workloads/movies-subset-hf-embeddings.json
  workloads/settings-add-embeddings.json
  workloads/settings-add-remove-filters.json
  workloads/settings-proximity-precision.json
  workloads/settings-remove-add-swap-searchable.json
  workloads/settings-typo.json
Labels: skip changelog

#4631 Split the field id map from the weight of each fields
  index-scheduler/src/utils.rs
  meilisearch/src/search.rs
  meilisearch/src/search_queue.rs
  meilisearch/tests/search/hybrid.rs
  meilisearch/tests/search/mod.rs
  meilisearch/tests/search/restrict_searchable.rs
  meilisearch/tests/snapshot/mod.rs
  milli/examples/search.rs
  milli/src/error.rs
  milli/src/fieldids_weights_map.rs
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/search/mod.rs
  milli/src/search/new/bucket_sort.rs
  milli/src/search/new/db_cache.rs
  milli/src/search/new/exact_attribute.rs
  milli/src/search/new/matches/matching_words.rs
  milli/src/search/new/matches/mod.rs
  milli/src/search/new/mod.rs
  milli/src/search/new/query_term/parse_query.rs
  milli/src/search/new/ranking_rule_graph/fid/mod.rs
  milli/src/search/new/tests/attribute_fid.rs
  milli/src/search/new/tests/snapshots/milli__search__new__tests__attribute_fid__attribute_fid_ngrams-4.snap
  milli/src/snapshot_tests.rs
  milli/src/update/index_documents/extract/extract_docid_word_positions.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/settings.rs
Labels: performance, search relevancy, indexing, settings diff-indexing

#4544 Stream documents
  Cargo.lock
  index-scheduler/src/batch.rs
  index-scheduler/src/lib.rs
  meilisearch-auth/src/store.rs
  meilisearch-types/src/error.rs
  meilisearch/Cargo.toml
  meilisearch/src/routes/indexes/documents.rs
  meilisearch/src/routes/mod.rs
  meilitool/src/main.rs
  milli/Cargo.toml
  milli/fuzz/.gitignore
  milli/src/error.rs
  milli/src/index.rs
  milli/src/update/facet/mod.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/typed_chunk.rs
Labels: performance, CPU/RAM usage

#4644 Revert "Stream documents" and keep heed+arroy to the latest verion
  Cargo.lock
  meilisearch/Cargo.toml
  meilisearch/src/routes/indexes/documents.rs
  meilisearch/src/routes/mod.rs
Labels: skip changelog

#4642 Index the _geo fields when changing the setting while there is already documents in the DB
  meilisearch/tests/search/geo.rs
  milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs
  milli/src/update/index_documents/extract/extract_geo_points.rs
  milli/src/update/index_documents/extract/mod.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/settings.rs
Labels: bug, geo search, settings diff-indexing

#4646 Reduce `Transform`'s disk usage
  meilisearch/tests/search/mod.rs
  milli/src/heed_codec/roaring_bitmap/cbo_roaring_bitmap_codec.rs
  milli/src/lib.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/transform.rs
  milli/src/update/settings.rs
Labels: enhancement

#4663 Bring back release v1.8.1 into main
  meilisearch/tests/search/geo.rs
  milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs
  milli/src/update/index_documents/extract/extract_geo_points.rs
  milli/src/update/index_documents/extract/mod.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/settings.rs
Labels: skip changelog

#4664 Update README.md
  README.md
Labels: documentation
