Repository meilisearch/meilisearch, pull requests merged in 2024-06, with the labels that each got.

#4656 Adding a new `searchableAttribute` no longer re-index all the attributes
  milli/src/update/del_add.rs
  milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs
  milli/src/update/index_documents/extract/extract_word_pair_proximity_docids.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/transform.rs
  milli/src/update/index_documents/typed_chunk.rs
  milli/src/update/settings.rs
  workloads/embeddings-movies-subset-hf.json
  workloads/embeddings-settings-add.json
Labels: settings diff-indexing

#4681 Fix concurrency issue
  meilisearch/src/search_queue.rs
Labels: bug

#4691 Add june 11th webinar banner
  README.md
Labels: skip changelog

#4682 Speed Up Filter ANDs operations
  Cargo.lock
  milli/src/heed_codec/facet/mod.rs
  milli/src/heed_codec/roaring_bitmap/cbo_roaring_bitmap_codec.rs
  milli/src/search/facet/facet_distribution_iter.rs
  milli/src/search/facet/facet_range_search.rs
  milli/src/search/facet/facet_sort_ascending.rs
  milli/src/search/facet/facet_sort_descending.rs
  milli/src/search/facet/filter.rs
  milli/src/search/facet/mod.rs
  milli/src/search/new/mod.rs
Labels: performance, filtering

#4649 Don't store the vectors in the documents database
  Cargo.lock
  dump/src/reader/snapshots/dump__reader__test__import_dump_v6_with_vectors-6.snap
  dump/src/reader/snapshots/dump__reader__test__import_dump_v6_with_vectors-7.snap
  dump/src/reader/v3/settings.rs
  dump/src/reader/v4/settings.rs
  dump/src/reader/v5/tasks.rs
  dump/tests/assets/v6-with-vectors.dump
  index-scheduler/Cargo.toml
  index-scheduler/src/batch.rs
  index-scheduler/src/lib.rs
  index-scheduler/src/snapshots/index_scheduler__tests__import_vectors-15.snap
  index-scheduler/src/snapshots/index_scheduler__tests__import_vectors-22.snap
  index-scheduler/src/snapshots/index_scheduler__tests__import_vectors-5.snap
  index-scheduler/src/snapshots/index_scheduler__tests__import_vectors-8.snap
  index-scheduler/src/snapshots/index_scheduler__tests__settings_update-5.snap
  index-scheduler/src/snapshots/lib.rs/import_vectors_first_and_embedder_later/documents after initial push.snap
  meilisearch-types/src/error.rs
  meilisearch-types/src/settings.rs
  meilisearch/src/analytics/mod.rs
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/routes/indexes/documents.rs
  meilisearch/src/routes/indexes/facet_search.rs
  meilisearch/src/routes/indexes/search.rs
  meilisearch/src/routes/indexes/similar.rs
  meilisearch/src/routes/multi_search.rs
  meilisearch/src/search.rs
  meilisearch/tests/common/index.rs
  meilisearch/tests/common/mod.rs
  meilisearch/tests/documents/errors.rs
  meilisearch/tests/documents/get_documents.rs
  meilisearch/tests/dumps/mod.rs
  meilisearch/tests/dumps/snapshots/mod.rs/generate_and_import_dump_containing_vectors/1.snap
  meilisearch/tests/dumps/snapshots/mod.rs/generate_and_import_dump_containing_vectors/2.snap
  meilisearch/tests/integration.rs
  meilisearch/tests/search/errors.rs
  meilisearch/tests/search/hybrid.rs
  meilisearch/tests/search/mod.rs
  meilisearch/tests/similar/errors.rs
  meilisearch/tests/similar/mod.rs
  meilisearch/tests/vector/mod.rs
  meilisearch/tests/vector/settings.rs
  milli/Cargo.toml
  milli/src/fieldids_weights_map.rs
  milli/src/fields_ids_map.rs
  milli/src/index.rs
  milli/src/search/new/logger/visual.rs
  milli/src/search/new/tests/snapshots/milli__search__new__tests__attribute_fid__attribute_fid_ngrams.snap
  milli/src/snapshots/index.rs/initial_field_distribution/1/field_distribution.snap
  milli/src/snapshots/index.rs/initial_field_distribution/field_distribution.snap
  milli/src/update/clear_documents.rs
  milli/src/update/index_documents/extract/extract_vector_points.rs
  milli/src/update/index_documents/extract/mod.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/transform.rs
  milli/src/update/index_documents/typed_chunk.rs
  milli/src/update/settings.rs
  milli/src/vector/mod.rs
  milli/src/vector/parsed_vectors.rs
  milli/src/vector/settings.rs
  xtask/Cargo.toml
Labels: performance, breaking change, CPU/RAM usage, experimental feature, disk space usage

#4705 Revert "Add june 11th webinar banner"
  README.md
Labels: skip changelog

#4713 Speed up facet distribution
  milli/src/search/facet/facet_distribution_iter.rs
  milli/src/update/index_documents/extract/extract_vector_points.rs
Labels: performance, filtering

#4715 Build all arroy indexes that need to be built
  Cargo.lock
  index-scheduler/Cargo.toml
  index-scheduler/src/lib.rs
  meilisearch/tests/common/mod.rs
  meilisearch/tests/vector/mod.rs
  meilisearch/tests/vector/snapshots/mod.rs/add_remove_one_vector_4588/document-added.snap
  meilisearch/tests/vector/snapshots/mod.rs/add_remove_one_vector_4588/document-deleted.snap
  meilisearch/tests/vector/snapshots/mod.rs/add_remove_one_vector_4588/settings-processed.snap
  milli/Cargo.toml
  milli/src/error.rs
  milli/src/index.rs
  milli/src/update/index_documents/mod.rs
Labels: bug, experimental feature

#4721 Update README.md
  README.md
Labels: documentation

#4725 Store primary key as String when Number exceeds i64 range
  meilisearch/tests/documents/add_documents.rs
  milli/src/documents/primary_key.rs
Labels: bug, error handler

#4730 fix a 100% flaky test
  meilisearch/tests/tasks/mod.rs
Labels: maintenance

#4716 Fix bad http status and error message on wrong payload
  meilisearch/src/error.rs
  meilisearch/tests/documents/add_documents.rs
Labels: bug, error handler

#4703 Update yaup
  Cargo.lock
  meilisearch/Cargo.toml
  meilisearch/tests/common/index.rs
  meilisearch/tests/search/errors.rs
  meilisearch/tests/similar/errors.rs
Labels: maintenance

#4724 Improve tenant token error messages
  meilisearch-auth/src/lib.rs
  meilisearch/src/extractors/authentication/mod.rs
  meilisearch/tests/auth/authorization.rs
  meilisearch/tests/auth/errors.rs
  meilisearch/tests/auth/tenant_token.rs
  meilisearch/tests/auth/tenant_token_multi_search.rs
  meilisearch/tests/common/mod.rs
Labels: enhancement, error handler

#4740 Make `embeddings` optional and improve error message for `regenerate`
  meilisearch-types/src/error.rs
  meilisearch/tests/vector/mod.rs
  milli/src/error.rs
  milli/src/vector/parsed_vectors.rs
Labels: error handler, experimental feature
