Repository meilisearch/meilisearch, pull requests merged in 2024-07, with the labels that each got.

#4781 Correct apk usages in Dockerfile
  Dockerfile
Labels: maintenance

#4786 Update dependencies
  .github/workflows/test-suite.yml
  CONTRIBUTING.md
  Cargo.lock
  Dockerfile
  benchmarks/Cargo.toml
  build-info/Cargo.toml
  dump/Cargo.toml
  dump/src/reader/compat/v2_to_v3.rs
  dump/src/reader/compat/v3_to_v4.rs
  dump/src/reader/compat/v4_to_v5.rs
  dump/src/reader/compat/v5_to_v6.rs
  dump/src/reader/mod.rs
  dump/src/reader/v2/mod.rs
  dump/src/reader/v3/mod.rs
  dump/src/reader/v4/mod.rs
  dump/src/reader/v5/mod.rs
  dump/src/writer.rs
  file-store/Cargo.toml
  filter-parser/Cargo.toml
  filter-parser/src/lib.rs
  fuzzers/Cargo.toml
  index-scheduler/Cargo.toml
  meili-snap/Cargo.toml
  meilisearch-auth/Cargo.toml
  meilisearch-types/Cargo.toml
  meilisearch/Cargo.toml
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/error.rs
  meilisearch/src/lib.rs
  meilisearch/src/option.rs
  meilisearch/src/routes/indexes/documents.rs
  meilisearch/src/search.rs
  meilisearch/tests/auth/errors.rs
  meilisearch/tests/common/server.rs
  meilisearch/tests/documents/add_documents.rs
  meilisearch/tests/documents/get_documents.rs
  meilisearch/tests/index/create_index.rs
  meilitool/Cargo.toml
  milli/Cargo.toml
  milli/src/heed_codec/roaring_bitmap_length/roaring_bitmap_len_codec.rs
  milli/src/index.rs
  milli/src/search/new/query_graph.rs
  milli/src/update/available_documents_ids.rs
  milli/src/update/index_documents/mod.rs
  rust-toolchain.toml
  tracing-trace/Cargo.toml
  tracing-trace/src/processor/firefox_profiler.rs
  tracing-trace/src/processor/fmt.rs
  xtask/Cargo.toml
Labels: dependencies, maintenance

#4626 Edit Documents with Rhai
  Cargo.lock
  dump/src/lib.rs
  index-scheduler/src/autobatcher.rs
  index-scheduler/src/batch.rs
  index-scheduler/src/features.rs
  index-scheduler/src/insta_snapshot.rs
  index-scheduler/src/lib.rs
  index-scheduler/src/utils.rs
  meilisearch-types/src/deserr/mod.rs
  meilisearch-types/src/error.rs
  meilisearch-types/src/features.rs
  meilisearch-types/src/task_view.rs
  meilisearch-types/src/tasks.rs
  meilisearch/src/analytics/mock_analytics.rs
  meilisearch/src/analytics/mod.rs
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/routes/features.rs
  meilisearch/src/routes/indexes/documents.rs
  meilisearch/src/routes/tasks.rs
  meilisearch/tests/documents/get_documents.rs
  meilisearch/tests/dumps/mod.rs
  meilisearch/tests/features/mod.rs
  meilisearch/tests/search/hybrid.rs
  meilisearch/tests/settings/get_settings.rs
  meilisearch/tests/similar/mod.rs
  meilisearch/tests/tasks/errors.rs
  meilisearch/tests/vector/mod.rs
  meilisearch/tests/vector/settings.rs
  milli/Cargo.toml
  milli/src/error.rs
  milli/src/lib.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/parallel.rs
Labels: prototype available

#4805 Log the time to index a batch of task
  index-scheduler/src/batch.rs
Labels: maintenance

#4804 Implements the experimental contains filter operator
  Cargo.lock
  filter-parser/src/condition.rs
  filter-parser/src/error.rs
  filter-parser/src/lib.rs
  filter-parser/src/value.rs
  index-scheduler/src/features.rs
  meilisearch-types/src/features.rs
  meilisearch/src/analytics/segment_analytics.rs
  meilisearch/src/error.rs
  meilisearch/src/option.rs
  meilisearch/src/routes/features.rs
  meilisearch/src/routes/indexes/documents.rs
  meilisearch/src/routes/indexes/facet_search.rs
  meilisearch/src/routes/indexes/search.rs
  meilisearch/src/routes/indexes/similar.rs
  meilisearch/src/routes/multi_search.rs
  meilisearch/src/search/federated.rs
  meilisearch/src/search/mod.rs
  meilisearch/tests/common/mod.rs
  meilisearch/tests/documents/errors.rs
  meilisearch/tests/documents/get_documents.rs
  meilisearch/tests/dumps/mod.rs
  meilisearch/tests/features/mod.rs
  meilisearch/tests/search/errors.rs
  meilisearch/tests/search/hybrid.rs
  meilisearch/tests/search/mod.rs
  meilisearch/tests/settings/get_settings.rs
  meilisearch/tests/similar/errors.rs
  meilisearch/tests/similar/mod.rs
  meilisearch/tests/vector/mod.rs
  meilisearch/tests/vector/settings.rs
  milli/Cargo.toml
  milli/src/index.rs
  milli/src/search/facet/filter.rs
Labels: experimental feature

#4806 Update rustls as much as possible
  Cargo.lock
  meilisearch/Cargo.toml
  meilisearch/src/main.rs
  meilisearch/src/option.rs
Labels: maintenance

#4812 Allow `MEILI_NO_VERGEN` env var to skip vergen
  CONTRIBUTING.md
  build-info/build.rs
Labels: maintenance

#4815 Rest embedder api mk2
  Cargo.lock
  index-scheduler/src/lib.rs
  index-scheduler/src/snapshots/index_scheduler__tests__import_vectors-2.snap
  index-scheduler/src/snapshots/index_scheduler__tests__import_vectors-5.snap
  index-scheduler/src/snapshots/index_scheduler__tests__import_vectors.snap
  index-scheduler/src/snapshots/index_scheduler__tests__settings_update-2.snap
  index-scheduler/src/snapshots/index_scheduler__tests__settings_update-5.snap
  index-scheduler/src/snapshots/index_scheduler__tests__settings_update.snap
  index-scheduler/src/snapshots/lib.rs/import_vectors/Intel to kefir succeeds.snap
  index-scheduler/src/snapshots/lib.rs/import_vectors/Intel to kefir.snap
  index-scheduler/src/snapshots/lib.rs/import_vectors/adding Intel succeeds.snap
  index-scheduler/src/snapshots/lib.rs/import_vectors/after adding Intel.snap
  index-scheduler/src/snapshots/lib.rs/import_vectors/after_registering_settings_task_vectors.snap
  index-scheduler/src/snapshots/lib.rs/import_vectors/settings_update_processed_vectors.snap
  index-scheduler/src/snapshots/lib.rs/test_settings_update/after_registering_settings_task.snap
  index-scheduler/src/snapshots/lib.rs/test_settings_update/settings_update_processed.snap
  meilisearch/Cargo.toml
  meilisearch/tests/common/mod.rs
  meilisearch/tests/search/hybrid.rs
  meilisearch/tests/settings/get_settings.rs
  meilisearch/tests/vector/mod.rs
  meilisearch/tests/vector/rest.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/settings.rs
  milli/src/vector/error.rs
  milli/src/vector/json_template.rs
  milli/src/vector/mod.rs
  milli/src/vector/ollama.rs
  milli/src/vector/openai.rs
  milli/src/vector/rest.rs
  milli/src/vector/settings.rs
Labels: breaking change, blocks vector store stabilization

#4808 Make the tests run faster
  index-scheduler/src/insta_snapshot.rs
  index-scheduler/src/lib.rs
  meilisearch/tests/auth/mod.rs
  meilisearch/tests/auth/tenant_token.rs
  meilisearch/tests/common/index.rs
  meilisearch/tests/common/mod.rs
  meilisearch/tests/common/server.rs
  meilisearch/tests/documents/add_documents.rs
  meilisearch/tests/documents/errors.rs
  meilisearch/tests/dumps/snapshots/mod.rs/generate_and_import_dump_containing_vectors/1.snap
  meilisearch/tests/dumps/snapshots/mod.rs/generate_and_import_dump_containing_vectors/2.snap
  meilisearch/tests/index/errors.rs
  meilisearch/tests/logs/error.rs
  meilisearch/tests/search/errors.rs
  meilisearch/tests/search/mod.rs
  meilisearch/tests/search/multi.rs
  meilisearch/tests/search/pagination.rs
  meilisearch/tests/search/restrict_searchable.rs
  meilisearch/tests/search/snapshots/distinct.rs/distinct_at_search_time/succeed.snap
  meilisearch/tests/settings/errors.rs
  meilisearch/tests/swap_indexes/errors.rs
  meilisearch/tests/tasks/errors.rs
  meilisearch/tests/tasks/mod.rs
  meilisearch/tests/vector/mod.rs
  meilisearch/tests/vector/rest.rs
  meilisearch/tests/vector/settings.rs
  meilisearch/tests/vector/snapshots/mod.rs/add_remove_one_vector_4588/document-added.snap
  meilisearch/tests/vector/snapshots/mod.rs/add_remove_one_vector_4588/document-deleted.snap
  meilisearch/tests/vector/snapshots/mod.rs/add_remove_one_vector_4588/settings-processed.snap
  milli/src/search/facet/filter.rs
Labels: maintenance
