Repository meilisearch/meilisearch, pull requests merged in 2025-04, with the labels that each got.

#5471 Support EC private key
  crates/meilisearch/src/option.rs
Labels: enhancement, no db change

#5313 fix for rankingScoreThreshold changes the results' ranking
  crates/milli/src/search/new/bucket_sort.rs
Labels: no db change

#5486 Update network URL validation error message format to match expected
  crates/meilisearch/src/routes/network.rs
  crates/meilisearch/tests/network/mod.rs
Labels: no db change

#5492 make meilisearch accept cancelation tasks even when the disk is full
  crates/index-scheduler/src/lib.rs
  crates/index-scheduler/src/queue/mod.rs
  crates/index-scheduler/src/queue/test.rs
Labels: enhancement, no db change

#5509 Bring back changes from v1.14.0 to main
  Cargo.lock
  crates/dump/src/lib.rs
  crates/index-scheduler/Cargo.toml
  crates/index-scheduler/src/insta_snapshot.rs
  crates/index-scheduler/src/lib.rs
  crates/index-scheduler/src/processing.rs
  crates/index-scheduler/src/queue/mod.rs
  crates/index-scheduler/src/queue/test.rs
  crates/index-scheduler/src/scheduler/mod.rs
  crates/index-scheduler/src/scheduler/process_batch.rs
  crates/index-scheduler/src/scheduler/process_index_operation.rs
  crates/meilisearch-types/src/batches.rs
  crates/meilisearch-types/src/error.rs
  crates/meilisearch/Cargo.toml
  crates/meilisearch/src/analytics/segment_analytics.rs
  crates/meilisearch/src/lib.rs
  crates/meilisearch/src/option.rs
  crates/meilisearch/src/routes/indexes/mod.rs
  crates/meilisearch/tests/batches/mod.rs
  crates/meilisearch/tests/documents/add_documents.rs
  crates/meilisearch/tests/documents/delete_documents.rs
  crates/meilisearch/tests/dumps/mod.rs
  crates/meilisearch/tests/search/mod.rs
  crates/meilisearch/tests/stats/mod.rs
  crates/meilisearch/tests/upgrade/v1_12/v1_12_0.rs
  crates/meilisearch/tests/vector/mod.rs
  crates/milli/src/database_stats.rs
  crates/milli/src/error.rs
  crates/milli/src/index.rs
  crates/milli/src/progress.rs
  crates/milli/src/search/new/bucket_sort.rs
  crates/milli/src/search/new/query_term/compute_derivations.rs
  crates/milli/src/update/index_documents/mod.rs
  crates/milli/src/update/new/document_change.rs
  crates/milli/src/update/new/extract/faceted/extract_facets.rs
  crates/milli/src/update/new/extract/vectors/mod.rs
  crates/milli/src/update/new/indexer/extract.rs
  crates/milli/src/update/new/indexer/mod.rs
  crates/milli/src/update/new/indexer/post_processing.rs
  crates/milli/src/update/new/indexer/write.rs
  crates/milli/src/update/new/merger.rs
  crates/milli/src/update/new/steps.rs
  crates/milli/src/update/settings.rs
Labels: db change

#5498 Stop compacting the snapshot
  crates/index-scheduler/src/scheduler/process_snapshot_creation.rs
Labels: no db change

#5487 fix ranking rules after _geo do not work
  crates/meilisearch/tests/documents/add_documents.rs
  crates/milli/src/search/hybrid.rs
  crates/milli/src/search/mod.rs
  crates/milli/src/search/new/geo_sort.rs
  crates/milli/src/search/new/matches/mod.rs
  crates/milli/src/search/new/mod.rs
  crates/milli/src/search/new/tests/geo_sort.rs
  crates/milli/src/search/new/tests/snapshots/milli__search__new__tests__geo_sort__geo_sort_with_following_ranking_rules-2.snap
  crates/milli/src/search/new/tests/snapshots/milli__search__new__tests__geo_sort__geo_sort_with_following_ranking_rules-4.snap
Labels: bug, no db change

#5513 Bump prometheus protobuf
  Cargo.lock
  crates/meilisearch/Cargo.toml
  crates/meilisearch/src/middleware.rs
Labels: security, no db change

#5519 Fix ruleset workflow
  .github/workflows/milestone-workflow.yml
Labels: no db change

#5520 Remove ProductHunt banner
  README.md
Labels: no db change

#5512 Task queue metrics
  assets/grafana-dashboard.json
  crates/index-scheduler/src/lib.rs
  crates/meilisearch/src/metrics.rs
  crates/meilisearch/src/routes/metrics.rs
Labels: no db change

#5530 Rename `batcherStoppedBecause` to `batchCreationComplete`
  crates/meilisearch-types/src/batch_view.rs
  crates/meilisearch/tests/batches/mod.rs
  crates/meilisearch/tests/dumps/snapshots/mod.rs/import_dump_v6_containing_batches_and_enqueued_tasks/batches.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterEnqueuedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterFinishedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterStartedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_batchUids_equal_10.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_beforeEnqueuedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_beforeFinishedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_beforeStartedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_canceledBy_equal_19.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_statuses_equal_canceled.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_uids_equal_10.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/the_whole_batch_queue_once_everything_has_been_processed.snap
Labels: no db change

#5533 Fix links and formatting in README.md for clarity and consistency
  README.md
Labels: no db change
