Repository meilisearch/meilisearch, pull requests merged in 2025-03, with the labels that each got.

#5365 Mention openAPI in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: maintenance

#5413 Make sure to delete useless prefixes
  crates/milli/src/update/new/words_prefix_docids.rs
Labels: bug

#5369 exhaustive facet search
  crates/meilisearch-types/src/error.rs
  crates/meilisearch/src/routes/indexes/facet_search.rs
  crates/meilisearch/tests/search/facet_search.rs
Labels: impacts docs, prototype available

#5406 Bump heed to v0.22 and arroy to v0.6
  Cargo.lock
  Cargo.toml
  crates/benchmarks/benches/indexing.rs
  crates/benchmarks/benches/utils.rs
  crates/fuzzers/src/bin/fuzz-indexing.rs
  crates/index-scheduler/Cargo.toml
  crates/index-scheduler/src/features.rs
  crates/index-scheduler/src/index_mapper/index_map.rs
  crates/index-scheduler/src/index_mapper/mod.rs
  crates/index-scheduler/src/lib.rs
  crates/index-scheduler/src/queue/batches.rs
  crates/index-scheduler/src/queue/mod.rs
  crates/index-scheduler/src/queue/tasks.rs
  crates/index-scheduler/src/scheduler/mod.rs
  crates/index-scheduler/src/scheduler/process_snapshot_creation.rs
  crates/index-scheduler/src/test_utils.rs
  crates/index-scheduler/src/upgrade/mod.rs
  crates/index-scheduler/src/versioning.rs
  crates/meilisearch-auth/src/dump.rs
  crates/meilisearch-auth/src/lib.rs
  crates/meilisearch-auth/src/store.rs
  crates/meilisearch-types/src/error.rs
  crates/meilisearch/src/lib.rs
  crates/meilisearch/src/search/mod.rs
  crates/meilisearch/tests/features/mod.rs
  crates/meilisearch/tests/upgrade/mod.rs
  crates/meilisearch/tests/upgrade/v1_12/v1_12_0.rs
  crates/meilitool/Cargo.toml
  crates/meilitool/src/main.rs
  crates/meilitool/src/upgrade/v1_10.rs
  crates/meilitool/src/upgrade/v1_11.rs
  crates/meilitool/src/upgrade/v1_12.rs
  crates/milli/Cargo.toml
  crates/milli/src/documents/mod.rs
  crates/milli/src/error.rs
  crates/milli/src/index.rs
  crates/milli/src/lib.rs
  crates/milli/src/search/new/tests/integration.rs
  crates/milli/src/update/facet/mod.rs
  crates/milli/src/update/index_documents/mod.rs
  crates/milli/src/update/new/indexer/document_changes.rs
  crates/milli/src/update/new/indexer/mod.rs
  crates/milli/src/update/new/indexer/write.rs
  crates/milli/src/update/upgrade/mod.rs
  crates/milli/src/update/upgrade/v1_13.rs
  crates/milli/src/update/upgrade/v1_14.rs
  crates/milli/src/vector/mod.rs
  crates/milli/tests/search/facet_distribution.rs
  crates/milli/tests/search/mod.rs
  crates/milli/tests/search/query_criteria.rs
  crates/milli/tests/search/typo_tolerance.rs
Labels: meilitool, db change

#5418 Cache embeddings in search
  Cargo.lock
  crates/index-scheduler/src/lib.rs
  crates/index-scheduler/src/scheduler/mod.rs
  crates/index-scheduler/src/scheduler/test_embedders.rs
  crates/index-scheduler/src/test_utils.rs
  crates/meilisearch/src/analytics/segment_analytics.rs
  crates/meilisearch/src/lib.rs
  crates/meilisearch/src/option.rs
  crates/meilisearch/src/search/mod.rs
  crates/meilisearch/tests/vector/openai.rs
  crates/milli/Cargo.toml
  crates/milli/src/search/hybrid.rs
  crates/milli/src/update/index_documents/mod.rs
  crates/milli/src/update/settings.rs
  crates/milli/src/vector/composite.rs
  crates/milli/src/vector/hf.rs
  crates/milli/src/vector/mod.rs
  crates/milli/src/vector/ollama.rs
  crates/milli/src/vector/openai.rs
  crates/milli/src/vector/rest.rs
Labels: performance

#5407 Geo update bug
  crates/meilisearch/tests/documents/add_documents.rs
  crates/milli/src/update/new/document_change.rs
  crates/milli/src/update/new/extract/faceted/extract_facets.rs
Labels: bug, indexing, geo search, indexer-2024-edition

#5455 Fix the Product Hunt link
  README.md
Labels: no db change

#5456 Fix CI to work with merge queues
  .github/workflows/test-suite.yml
  CONTRIBUTING.md
  README.md
  bors.toml
Labels: no db change

#5454 Update Charabia v0.9.3
  Cargo.lock
  crates/milli/Cargo.toml
Labels: no db change

#5402 Avoid reindexing searchable order changes
  crates/milli/src/update/settings.rs
Labels: prototype available, no db change

#5458 Fix the PH link on the README
  README.md
Labels: no db change

#5446 Fix _matchesPosition length calculate
  crates/meilisearch/tests/search/formatted.rs
  crates/milli/src/search/new/matches/mod.rs
Labels: bug, no db change

#5457 Show database sizes batches
  Cargo.lock
  crates/dump/src/lib.rs
  crates/index-scheduler/Cargo.toml
  crates/index-scheduler/src/insta_snapshot.rs
  crates/index-scheduler/src/processing.rs
  crates/index-scheduler/src/scheduler/mod.rs
  crates/index-scheduler/src/scheduler/process_batch.rs
  crates/index-scheduler/src/scheduler/process_index_operation.rs
  crates/meilisearch-types/src/batches.rs
  crates/meilisearch/Cargo.toml
  crates/meilisearch/tests/batches/mod.rs
  crates/meilisearch/tests/dumps/mod.rs
  crates/meilisearch/tests/upgrade/v1_12/v1_12_0.rs
  crates/milli/src/index.rs
Labels: db change

#5466 Update charabia v0.9.3
  Cargo.lock
  crates/milli/Cargo.toml
Labels: no db change

#5478 Enforce embedding dimensions
  crates/meilisearch-types/src/error.rs
  crates/meilisearch/tests/vector/mod.rs
  crates/milli/src/error.rs
  crates/milli/src/update/new/extract/vectors/mod.rs
Labels: no db change
