Repository meilisearch/meilisearch, pull requests merged in 2025-01, with the labels that each got.

#5211 Update README.md with AI integrations (langchain & MCP)
  README.md
Labels: skip changelog

#4867 Autogenerate the openAPI spec
  Cargo.lock
  crates/index-scheduler/src/scheduler/test.rs
  crates/index-scheduler/src/scheduler/test_embedders.rs
  crates/meilisearch-types/Cargo.toml
  crates/meilisearch-types/src/batch_view.rs
  crates/meilisearch-types/src/batches.rs
  crates/meilisearch-types/src/error.rs
  crates/meilisearch-types/src/facet_values_sort.rs
  crates/meilisearch-types/src/index_uid.rs
  crates/meilisearch-types/src/keys.rs
  crates/meilisearch-types/src/locales.rs
  crates/meilisearch-types/src/settings.rs
  crates/meilisearch-types/src/star_or.rs
  crates/meilisearch-types/src/task_view.rs
  crates/meilisearch-types/src/tasks.rs
  crates/meilisearch/Cargo.toml
  crates/meilisearch/src/routes/api_key.rs
  crates/meilisearch/src/routes/batches.rs
  crates/meilisearch/src/routes/dump.rs
  crates/meilisearch/src/routes/features.rs
  crates/meilisearch/src/routes/indexes/documents.rs
  crates/meilisearch/src/routes/indexes/facet_search.rs
  crates/meilisearch/src/routes/indexes/mod.rs
  crates/meilisearch/src/routes/indexes/search.rs
  crates/meilisearch/src/routes/indexes/settings.rs
  crates/meilisearch/src/routes/indexes/settings_analytics.rs
  crates/meilisearch/src/routes/indexes/similar.rs
  crates/meilisearch/src/routes/logs.rs
  crates/meilisearch/src/routes/metrics.rs
  crates/meilisearch/src/routes/mod.rs
  crates/meilisearch/src/routes/multi_search.rs
  crates/meilisearch/src/routes/open_api_utils.rs
  crates/meilisearch/src/routes/snapshot.rs
  crates/meilisearch/src/routes/swap_indexes.rs
  crates/meilisearch/src/routes/tasks.rs
  crates/meilisearch/src/search/federated.rs
  crates/meilisearch/src/search/mod.rs
  crates/meilisearch/tests/search/hybrid.rs
  crates/meilisearch/tests/settings/get_settings.rs
  crates/meilisearch/tests/vector/binary_quantized.rs
  crates/milli/Cargo.toml
  crates/milli/src/localized_attributes_rules.rs
  crates/milli/src/progress.rs
  crates/milli/src/search/new/matches/mod.rs
  crates/milli/src/vector/mod.rs
  crates/milli/src/vector/settings.rs
Labels: maintenance

#5216 Add support for GITHUB_TOKEN authentication in installation script
  download-latest.sh
Labels: tooling

#5224 Fix facet distribution
  crates/meilitool/Cargo.toml
  crates/meilitool/src/upgrade/mod.rs
  crates/meilitool/src/upgrade/v1_10.rs
  crates/meilitool/src/upgrade/v1_11.rs
  crates/meilitool/src/upgrade/v1_12.rs
  crates/milli/src/update/index_documents/mod.rs
  crates/milli/src/update/new/extract/documents.rs
  crates/milli/src/update/new/mod.rs
  crates/milli/src/update/new/reindex.rs
Labels: meilitool

#5231 Improve openapi
  crates/meilisearch/src/routes/api_key.rs
  crates/meilisearch/src/routes/batches.rs
  crates/meilisearch/src/routes/dump.rs
  crates/meilisearch/src/routes/features.rs
  crates/meilisearch/src/routes/indexes/mod.rs
  crates/meilisearch/src/routes/indexes/settings.rs
  crates/meilisearch/src/routes/metrics.rs
  crates/meilisearch/src/routes/mod.rs
  crates/meilisearch/src/routes/multi_search.rs
  crates/meilisearch/src/routes/snapshot.rs
  crates/meilisearch/src/routes/swap_indexes.rs
Labels: maintenance

#5239 Fix corrupted task queue errors on index creation
  crates/index-scheduler/src/index_mapper/mod.rs
  crates/index-scheduler/src/scheduler/test.rs
Labels: bug

#5246 Fix dump import
  crates/index-scheduler/src/batch.rs
  crates/index-scheduler/src/lib.rs
  crates/meilitool/src/main.rs
  crates/meilitool/src/upgrade/mod.rs
Labels: meilitool

#5284 Fix [5281] Removed CouldNotUpgrade from error file
  crates/meilisearch-types/src/error.rs
Labels: maintenance, error handler

#5210 Improve test performance of get_index.rs
  crates/meilisearch/tests/common/server.rs
  crates/meilisearch/tests/index/get_index.rs
Labels: maintenance

#5272 Fix Batches Deletion and flaky tests
  crates/index-scheduler/src/insta_snapshot.rs
  crates/index-scheduler/src/queue/batches.rs
  crates/index-scheduler/src/queue/batches_test.rs
  crates/index-scheduler/src/scheduler/process_batch.rs
  crates/index-scheduler/src/scheduler/snapshots/test.rs/task_deletion_delete_same_task_twice/task_deletion_processed.snap
  crates/index-scheduler/src/scheduler/snapshots/test.rs/task_deletion_deleteable/task_deletion_processed.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/after_removing_the_upgrade_tasks.snap
  crates/index-scheduler/src/utils.rs
  crates/meilisearch-types/src/batches.rs
  crates/meilisearch/tests/batches/mod.rs
Labels: bug

#5291 Fix Dotnet tests in sdks-tests.yml
  .github/workflows/sdks-tests.yml
Labels: maintenance

#5300 Improve unexpected panic message
  crates/index-scheduler/src/error.rs
  crates/index-scheduler/src/scheduler/mod.rs
  crates/index-scheduler/src/scheduler/process_batch.rs
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/panic_in_process_batch_for_index_creation/index_creation_failed.snap
Labels: error handler
