Repository meilisearch/meilisearch, pull requests merged in 2025-02, with the labels that each got.

#5140 Fix workload inversion
  workloads/hackernews-modify-facet-numbers.json
  workloads/hackernews-modify-facet-strings.json
Labels: maintenance, skip changelog

#5235 Introduce a compaction subcommand in meilitool
  crates/meilitool/src/main.rs
Labels: meilitool

#4970 Create a new export documents meilitool subcommand
  crates/meilitool/src/main.rs
Labels: meilitool

#5323 Exclude network time from processing ms
  crates/meilisearch/src/search/federated/perform.rs
Labels: skip changelog

#5316 Fix the dumpless upgrade corruption
  crates/index-scheduler/src/lib.rs
  crates/index-scheduler/src/scheduler/test_failure.rs
  crates/index-scheduler/src/versioning.rs
  crates/meilisearch-types/src/versioning.rs
  crates/meilisearch/src/lib.rs
  crates/milli/src/update/new/indexer/mod.rs
  crates/milli/src/update/upgrade/v1_12.rs
Labels: bug, version upgrade

#5310 Fix batch export/import dump
  crates/dump/README.md
  crates/dump/src/lib.rs
  crates/dump/src/reader/mod.rs
  crates/dump/src/reader/v6/mod.rs
  crates/dump/src/writer.rs
  crates/index-scheduler/src/dump.rs
  crates/index-scheduler/src/processing.rs
  crates/index-scheduler/src/scheduler/process_dump_creation.rs
  crates/meilisearch-types/src/batches.rs
  crates/meilisearch/src/lib.rs
  crates/meilisearch/tests/assets/v6_v1.13.0_batches_and_enqueued_tasks.dump
  crates/meilisearch/tests/common/server.rs
  crates/meilisearch/tests/dumps/data.rs
  crates/meilisearch/tests/dumps/mod.rs
  crates/meilisearch/tests/dumps/snapshots/mod.rs/import_dump_v6_containing_batches_and_enqueued_tasks/batches.snap
  crates/meilisearch/tests/dumps/snapshots/mod.rs/import_dump_v6_containing_batches_and_enqueued_tasks/tasks.snap
  crates/meilitool/src/main.rs
Labels: enhancement

#5324 Mention utoipa in sprint issues
  .github/ISSUE_TEMPLATE/sprint_issue.md
Labels: maintenance

#5336 Meilitool Hair Dryer
  crates/meilitool/src/main.rs
Labels: meilitool

#5342 Fix workload sha
  workloads/hackernews-modify-facet-numbers.json
  workloads/hackernews-modify-facet-strings.json
Labels: maintenance, skip changelog

#5346 Hotfix typo tolerance bug
  crates/meilisearch/tests/search/mod.rs
  crates/milli/src/search/new/query_term/compute_derivations.rs
Labels: bug
