Repository meilisearch/meilisearch, pull requests merged in 2025-08, with the labels that each got.

#5766 Release process change
  .github/ISSUE_TEMPLATE/new_feature_issue.md
  .github/pull_request_template.md
  .github/release-draft-template.yml
  .github/templates/dependency-issue.md
  .github/workflows/check-valid-milestone.yml
  .github/workflows/dependency-issue.yml
  .github/workflows/flaky-tests.yml
  .github/workflows/milestone-workflow.yml
  .github/workflows/release-drafter.yml
  .github/workflows/sdks-tests.yml
  .github/workflows/test-suite.yml
  CONTRIBUTING.md
  README.md
  documentation/experimental-features.md
  documentation/prototypes.md
  documentation/release.md
  documentation/versioning-policy.md
Labels: maintenance, no db change

#5783 Optimize the starts_with filter
  crates/benchmarks/Cargo.toml
  crates/benchmarks/benches/filter_starts_with.rs
  crates/filter-parser/src/lib.rs
  crates/index-scheduler/src/features.rs
  crates/meilisearch/tests/search/errors.rs
  crates/milli/src/search/facet/filter.rs
  crates/milli/src/search/new/tests/integration.rs
  crates/milli/tests/search/filters.rs
  crates/milli/tests/search/mod.rs
Labels: impacts docs, experimental feature, no db change

#5785 Webhook api
  crates/dump/src/reader/compat/v5_to_v6.rs
  crates/dump/src/reader/mod.rs
  crates/dump/src/reader/v6/mod.rs
  crates/dump/src/writer.rs
  crates/dump/tests/assets/v6-with-webhooks.dump
  crates/index-scheduler/src/features.rs
  crates/index-scheduler/src/insta_snapshot.rs
  crates/index-scheduler/src/lib.rs
  crates/index-scheduler/src/processing.rs
  crates/index-scheduler/src/scheduler/mod.rs
  crates/index-scheduler/src/scheduler/process_dump_creation.rs
  crates/index-scheduler/src/test_utils.rs
  crates/meilisearch-auth/src/store.rs
  crates/meilisearch-types/src/error.rs
  crates/meilisearch-types/src/keys.rs
  crates/meilisearch-types/src/lib.rs
  crates/meilisearch-types/src/webhooks.rs
  crates/meilisearch/src/lib.rs
  crates/meilisearch/src/option.rs
  crates/meilisearch/src/routes/mod.rs
  crates/meilisearch/src/routes/network.rs
  crates/meilisearch/src/routes/webhooks.rs
  crates/meilisearch/tests/auth/api_keys.rs
  crates/meilisearch/tests/auth/errors.rs
  crates/meilisearch/tests/common/server.rs
  crates/meilisearch/tests/tasks/webhook.rs
Labels: impacts docs, impacts integrations, db change

#5803 Minor docs update about release.md
  documentation/release.md
Labels: maintenance, no db change

#5806 Update version to v1.17.0
  Cargo.lock
  Cargo.toml
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/after_processing_everything.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/register_automatic_upgrade_task.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/registered_a_task_while_the_upgrade_task_is_enqueued.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/upgrade_task_failed.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/upgrade_task_failed_again.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/upgrade_task_succeeded.snap
  crates/meilisearch/tests/upgrade/mod.rs
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterEnqueuedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterFinishedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterStartedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterEnqueuedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterFinishedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterStartedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/the_whole_batch_queue_once_everything_has_been_processed.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/the_whole_task_queue_once_everything_has_been_processed.snap
  crates/milli/src/update/upgrade/mod.rs
  crates/milli/src/update/upgrade/v1_16.rs
Labels: no db change

#5810 Add category to release draft
  .github/release-draft-template.yml
Labels: documentation, no db change

#5817 fix the dumpless upgrade again
  crates/index-scheduler/src/upgrade/mod.rs
Labels: version upgrade, no db change

#5823 Publish OpenAPI file to release assets
  .github/workflows/publish-release-assets.yml
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  crates/openapi-generator/Cargo.toml
  crates/openapi-generator/src/main.rs
Labels: enhancement, no db change

#5830 Update version for v1.17.1
  Cargo.lock
  Cargo.toml
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/after_processing_everything.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/register_automatic_upgrade_task.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/registered_a_task_while_the_upgrade_task_is_enqueued.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/upgrade_task_failed.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/upgrade_task_failed_again.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/upgrade_task_succeeded.snap
  crates/meilisearch/tests/upgrade/mod.rs
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterEnqueuedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterFinishedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterStartedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterEnqueuedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterFinishedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterStartedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/the_whole_batch_queue_once_everything_has_been_processed.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/the_whole_task_queue_once_everything_has_been_processed.snap
Labels: skip changelog, no db change

#5741 Add Vector filters
  Cargo.lock
  crates/filter-parser/Cargo.toml
  crates/filter-parser/src/condition.rs
  crates/filter-parser/src/error.rs
  crates/filter-parser/src/lib.rs
  crates/filter-parser/src/value.rs
  crates/index-scheduler/src/scheduler/test_document_addition.rs
  crates/meilisearch/src/routes/indexes/documents.rs
  crates/meilisearch/src/routes/indexes/search_analytics.rs
  crates/meilisearch/src/routes/tasks.rs
  crates/meilisearch/src/search/mod.rs
  crates/meilisearch/tests/documents/errors.rs
  crates/meilisearch/tests/search/errors.rs
  crates/meilisearch/tests/search/filters.rs
  crates/meilisearch/tests/vector/mod.rs
  crates/meilisearch/tests/vector/rest.rs
  crates/milli/src/error.rs
  crates/milli/src/filterable_attributes_rules.rs
  crates/milli/src/search/facet/filter.rs
  crates/milli/src/search/facet/filter_vector.rs
  crates/milli/src/search/facet/mod.rs
  crates/milli/src/test_index.rs
  crates/milli/src/vector/db.rs
  crates/milli/src/vector/mod.rs
Labels: enhancement, impacts docs, impacts integrations, no db change

#5857 Fix license detection
  LICENSE-EE.md
  LICENSE.md
  README.md
  crates/meilisearch-types/src/enterprise_edition/mod.rs
  crates/meilisearch-types/src/enterprise_edition/network.rs
  crates/meilisearch/src/routes/indexes/enterprise_edition/mod.rs
  crates/meilisearch/src/routes/indexes/enterprise_edition/proxy.rs
  crates/milli/src/update/new/indexer/enterprise_edition/mod.rs
  crates/milli/src/update/new/indexer/enterprise_edition/sharding.rs
Labels: documentation, no db change
