Repository meilisearch/meilisearch, pull requests merged in 2025-07, with the labels that each got.

#5737 Fix the dumpless upgrade from v1.15 to v1.16 for request fragments
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_features/kefir_settings.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_features/search_with_retrieve_vectors.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterEnqueuedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterFinishedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterStartedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterEnqueuedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterFinishedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterStartedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/the_whole_batch_queue_once_everything_has_been_processed.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/the_whole_task_queue_once_everything_has_been_processed.snap
  crates/meilisearch/tests/upgrade/v1_12/v1_12_0.ms/auth/lock.mdb
  crates/meilisearch/tests/upgrade/v1_12/v1_12_0.ms/indexes/381abe91-f939-4b91-92f2-01a24c2e8e3d/data.mdb
  crates/meilisearch/tests/upgrade/v1_12/v1_12_0.ms/indexes/381abe91-f939-4b91-92f2-01a24c2e8e3d/lock.mdb
  crates/meilisearch/tests/upgrade/v1_12/v1_12_0.ms/tasks/data.mdb
  crates/meilisearch/tests/upgrade/v1_12/v1_12_0.ms/tasks/lock.mdb
  crates/meilisearch/tests/upgrade/v1_12/v1_12_0.rs
  crates/milli/src/update/upgrade/mod.rs
  crates/milli/src/update/upgrade/v1_15.rs
  crates/milli/src/update/upgrade/v1_16.rs
  crates/milli/src/vector/db.rs
Labels: no db change

#5753 Various fixes on the export route
  crates/index-scheduler/src/scheduler/process_export.rs
  crates/meilisearch/src/error.rs
Labels: no db change

#5756 Fix Rails CI
  .github/workflows/sdks-tests.yml
Labels: maintenance, no db change

#5703 tests: Use Server::wait_task() instead of Index::wait_task()
  crates/meilisearch/tests/auth/authorization.rs
  crates/meilisearch/tests/auth/tenant_token.rs
  crates/meilisearch/tests/auth/tenant_token_multi_search.rs
  crates/meilisearch/tests/batches/mod.rs
  crates/meilisearch/tests/common/index.rs
  crates/meilisearch/tests/common/mod.rs
  crates/meilisearch/tests/common/server.rs
  crates/meilisearch/tests/documents/add_documents.rs
  crates/meilisearch/tests/documents/delete_documents.rs
  crates/meilisearch/tests/documents/errors.rs
  crates/meilisearch/tests/documents/get_documents.rs
  crates/meilisearch/tests/dumps/mod.rs
  crates/meilisearch/tests/index/create_index.rs
  crates/meilisearch/tests/index/delete_index.rs
  crates/meilisearch/tests/index/get_index.rs
  crates/meilisearch/tests/index/update_index.rs
  crates/meilisearch/tests/search/multi/proxy.rs
  crates/meilisearch/tests/similar/errors.rs
  crates/meilisearch/tests/snapshot/mod.rs
  crates/meilisearch/tests/stats/mod.rs
  crates/meilisearch/tests/vector/binary_quantized.rs
  crates/meilisearch/tests/vector/mod.rs
  crates/meilisearch/tests/vector/ollama.rs
  crates/meilisearch/tests/vector/openai.rs
  crates/meilisearch/tests/vector/rest.rs
Labels: maintenance, no db change

#5710 Introduce filters in the chat completions
  crates/meilisearch-types/src/error.rs
  crates/meilisearch-types/src/features.rs
  crates/meilisearch/src/routes/chats/chat_completions.rs
  crates/meilisearch/src/routes/chats/settings.rs
Labels: no db change

#5626 tests: Faster batches:: IT tests
  crates/meilisearch/tests/batches/mod.rs
  crates/meilisearch/tests/common/mod.rs
Labels: maintenance, no db change

#3265 Sign container image using Cosign in keyless mode
  .github/workflows/publish-docker-images.yml
Labels: tooling, no db change

#5716 Allow sorting on the /documents route
  .gitignore
  crates/benchmarks/Cargo.toml
  crates/benchmarks/benches/sort.rs
  crates/benchmarks/benches/utils.rs
  crates/meilisearch-types/src/error.rs
  crates/meilisearch/db.snapshot
  crates/meilisearch/src/analytics/mock_analytics.rs
  crates/meilisearch/src/analytics/mod.rs
  crates/meilisearch/src/routes/indexes/documents.rs
  crates/meilisearch/src/search/federated/perform.rs
  crates/meilisearch/src/search/mod.rs
  crates/meilisearch/tests/common/index.rs
  crates/meilisearch/tests/documents/get_documents.rs
  crates/meilisearch/tests/vector/settings.rs
  crates/milli/src/asc_desc.rs
  crates/milli/src/documents/geo_sort.rs
  crates/milli/src/documents/mod.rs
  crates/milli/src/documents/sort.rs
  crates/milli/src/error.rs
  crates/milli/src/lib.rs
  crates/milli/src/search/mod.rs
  crates/milli/src/search/new/distinct.rs
  crates/milli/src/search/new/geo_sort.rs
  crates/milli/src/search/new/mod.rs
Labels: impacts docs, no db change

#5734 Tests for multimodal
  crates/meilisearch/tests/common/mod.rs
  crates/meilisearch/tests/common/server.rs
  crates/meilisearch/tests/search/multi/proxy.rs
  crates/meilisearch/tests/vector/fragments.rs
  crates/meilisearch/tests/vector/mod.rs
  crates/meilisearch/tests/vector/openai.rs
  crates/meilisearch/tests/vector/rest.rs
  crates/milli/src/update/settings.rs
  crates/milli/src/vector/composite.rs
Labels: no db change

#5754 Fix incorrect document count in stats after clearing all documents
  crates/milli/src/update/clear_documents.rs
Labels: no db change

#5761 Fix chat settings dumpless upgrade
  crates/meilisearch-types/src/features.rs
Labels: no db change

#5763 Regenerate all fragments when coming from a user provided vector
  crates/index-scheduler/src/scheduler/process_dump_creation.rs
  crates/index-scheduler/src/scheduler/process_export.rs
  crates/index-scheduler/src/scheduler/test_embedders.rs
  crates/meilisearch/db.snapshot
  crates/meilisearch/src/routes/indexes/documents.rs
  crates/meilisearch/src/search/mod.rs
  crates/meilitool/src/main.rs
  crates/milli/src/index.rs
  crates/milli/src/update/index_documents/extract/extract_vector_points.rs
  crates/milli/src/update/new/extract/vectors/mod.rs
  crates/milli/src/vector/mod.rs
Labels: no db change

#5770 fix: index chat settings `searchParameters` incorrectly set with `limit: 20` when sending empty object
  crates/milli/src/update/chat.rs
Labels: bug, no db change

#5780 Fix api key action inconsistencies
  crates/meilisearch-types/src/keys.rs
  crates/meilisearch/tests/auth/api_keys.rs
  crates/meilisearch/tests/auth/errors.rs
Labels: no db change

#5790 Adapt Go CI to recent change in the Go repo
  .github/workflows/sdks-tests.yml
Labels: maintenance, no db change

#5791 update mini-dashboard to v0.2.21
  crates/meilisearch/Cargo.toml
Labels: no db change
