Repository meilisearch/meilisearch, pull requests merged in 2025-09, with the labels that each got.

#5858 Display the progressTrace in real time
  crates/index-scheduler/src/queue/batches.rs
  crates/index-scheduler/src/queue/batches_test.rs
  crates/meilisearch/tests/vector/rest.rs
Labels: enhancement, no db change

#5883 Update to v1.20
  Cargo.lock
  Cargo.toml
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/after_processing_everything.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/register_automatic_upgrade_task.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/registered_a_task_while_the_upgrade_task_is_enqueued.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/upgrade_task_failed.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/upgrade_task_failed_again.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/upgrade_task_succeeded.snap
  crates/index-scheduler/src/upgrade/mod.rs
  crates/meilisearch/tests/upgrade/mod.rs
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterEnqueuedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterFinishedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterStartedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterEnqueuedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterFinishedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterStartedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/the_whole_batch_queue_once_everything_has_been_processed.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/the_whole_task_queue_once_everything_has_been_processed.snap
  crates/milli/src/update/upgrade/mod.rs
Labels: no db change

#5890 Update dumpless upgrade for v1.21
  Cargo.lock
  Cargo.toml
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/after_processing_everything.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/register_automatic_upgrade_task.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/registered_a_task_while_the_upgrade_task_is_enqueued.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/upgrade_task_failed.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/upgrade_task_failed_again.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/upgrade_task_succeeded.snap
  crates/index-scheduler/src/upgrade/mod.rs
  crates/meilisearch/tests/upgrade/mod.rs
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterEnqueuedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterFinishedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterStartedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterEnqueuedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterFinishedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterStartedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/the_whole_batch_queue_once_everything_has_been_processed.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/the_whole_task_queue_once_everything_has_been_processed.snap
  crates/milli/src/update/upgrade/mod.rs
Labels: skip changelog, no db change

#5892 increase rust version from 1.85 to 1.89
  .github/workflows/test-suite.yml
  Dockerfile
  crates/dump/src/reader/compat/v2_to_v3.rs
  crates/filter-parser/src/condition.rs
  crates/filter-parser/src/lib.rs
  crates/index-scheduler/src/dump.rs
  crates/index-scheduler/src/error.rs
  crates/index-scheduler/src/lib.rs
  crates/index-scheduler/src/queue/mod.rs
  crates/index-scheduler/src/scheduler/create_batch.rs
  crates/index-scheduler/src/scheduler/process_export.rs
  crates/index-scheduler/src/uuid_codec.rs
  crates/meilisearch-auth/src/store.rs
  crates/meilisearch/src/error.rs
  crates/meilisearch/src/lib.rs
  crates/meilisearch/src/search/federated/perform.rs
  crates/meilisearch/src/search/mod.rs
  crates/meilisearch/src/search_queue.rs
  crates/meilisearch/tests/auth/tenant_token_multi_search.rs
  crates/meilisearch/tests/vector/mod.rs
  crates/meilitool/src/uuid_codec.rs
  crates/milli/src/error.rs
  crates/milli/src/heed_codec/roaring_bitmap_length/roaring_bitmap_len_codec.rs
  crates/milli/src/lib.rs
  crates/milli/src/search/facet/facet_distribution_iter.rs
  crates/milli/src/search/facet/filter.rs
  crates/milli/src/search/facet/search.rs
  crates/milli/src/search/new/bucket_sort.rs
  crates/milli/src/search/new/ranking_rule_graph/cheapest_paths.rs
  crates/milli/src/search/new/small_bitmap.rs
  crates/milli/src/search/new/sort.rs
  crates/milli/src/update/new/channel.rs
  crates/milli/src/update/new/indexer/de.rs
  crates/milli/src/update/new/thread_local.rs
  crates/milli/src/vector/embedder/composite.rs
  crates/milli/src/vector/embedder/mod.rs
  rust-toolchain.toml
Labels: dependencies, maintenance, no db change

#5907 use the latest version of zerometry that supports collection, lines and multi-lines
  Cargo.lock
  crates/meilisearch/tests/documents/geojson/mod.rs
  crates/milli/Cargo.toml
Labels: no db change

#5908 Update version
  Cargo.lock
  Cargo.toml
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/after_processing_everything.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/register_automatic_upgrade_task.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/registered_a_task_while_the_upgrade_task_is_enqueued.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/upgrade_task_failed.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/upgrade_task_failed_again.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/upgrade_task_succeeded.snap
  crates/index-scheduler/src/upgrade/mod.rs
  crates/meilisearch/tests/upgrade/mod.rs
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterEnqueuedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterFinishedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterStartedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterEnqueuedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterFinishedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterStartedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/the_whole_batch_queue_once_everything_has_been_processed.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/the_whole_task_queue_once_everything_has_been_processed.snap
Labels: no db change

#5834 Minor improvement in OpenAPI CI
  .github/workflows/publish-release-assets.yml
Labels: maintenance, no db change
