Repository meilisearch/meilisearch, pull requests merged in 2025-05, with the labels that each got.

#5494 Deactivate numbers in typos
  crates/dump/src/reader/compat/v5_to_v6.rs
  crates/meilisearch-types/src/settings.rs
  crates/meilisearch/tests/dumps/mod.rs
  crates/meilisearch/tests/search/mod.rs
  crates/meilisearch/tests/settings/errors.rs
  crates/meilisearch/tests/settings/get_settings.rs
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_features/kefir_settings.snap
  crates/milli/src/disabled_typos_terms.rs
  crates/milli/src/index.rs
  crates/milli/src/lib.rs
  crates/milli/src/update/index_documents/extract/extract_word_docids.rs
  crates/milli/src/update/index_documents/typed_chunk.rs
  crates/milli/src/update/new/extract/searchable/extract_word_docids.rs
  crates/milli/src/update/new/indexer/mod.rs
  crates/milli/src/update/new/indexer/post_processing.rs
  crates/milli/src/update/settings.rs
  crates/milli/src/update/test_settings.rs
  crates/milli/src/update/upgrade/mod.rs
  crates/milli/src/update/upgrade/v1_15.rs
Labels: db change

#5523 Allow rollbacking updates
  crates/index-scheduler/src/error.rs
  crates/index-scheduler/src/index_mapper/mod.rs
  crates/index-scheduler/src/insta_snapshot.rs
  crates/index-scheduler/src/lib.rs
  crates/index-scheduler/src/processing.rs
  crates/index-scheduler/src/scheduler/create_batch.rs
  crates/index-scheduler/src/scheduler/process_batch.rs
  crates/index-scheduler/src/scheduler/process_upgrade/mod.rs
  crates/index-scheduler/src/test_utils.rs
  crates/index-scheduler/src/upgrade/mod.rs
  crates/index-scheduler/src/versioning.rs
  crates/meilisearch-types/src/tasks.rs
  crates/meilisearch-types/src/versioning.rs
  crates/meilisearch/src/lib.rs
  crates/meilisearch/tests/upgrade/mod.rs
  crates/meilitool/src/upgrade/mod.rs
  crates/milli/src/constants.rs
  crates/milli/src/index.rs
  crates/milli/src/snapshots/index.rs/bug_3007/geo_faceted_documents_ids.snap
  crates/milli/src/snapshots/index.rs/unexpected_extra_fields_in_geo_field/geo_faceted_documents_ids.snap
  crates/milli/src/snapshots/test_index.rs/bug_3007/geo_faceted_documents_ids.snap
  crates/milli/src/snapshots/test_index.rs/unexpected_extra_fields_in_geo_field/geo_faceted_documents_ids.snap
  crates/milli/src/test_index.rs
  crates/milli/src/update/upgrade/mod.rs
  crates/milli/src/update/upgrade/v1_13.rs
Labels: no db change

#5535 Allow lexicographic filtering of strings
  crates/milli/src/search/facet/filter.rs
Labels: no db change

#5552 Add v1.15 in index-scheduler upgrade
  crates/index-scheduler/src/upgrade/mod.rs
  crates/milli/src/update/upgrade/mod.rs
Labels: no db change

#5551 Only intern in case of single-typo when looking for single typoes
  crates/meilisearch/tests/search/mod.rs
  crates/milli/src/search/new/query_term/compute_derivations.rs
Labels: no db change

#5563 Fix swarmia deployement
  .github/workflows/publish-docker-images.yml
Labels: maintenance, no db change

#5564 Port to v1.15: Only intern in case of single-typo when looking for single typoes
  crates/meilisearch/tests/search/mod.rs
  crates/milli/src/search/new/query_term/compute_derivations.rs
Labels: no db change

#5560 Add an experimental cli flag to disable snapshot compaction
  crates/index-scheduler/src/lib.rs
  crates/index-scheduler/src/scheduler/mod.rs
  crates/index-scheduler/src/scheduler/process_snapshot_creation.rs
  crates/index-scheduler/src/test_utils.rs
  crates/meilisearch/src/analytics/segment_analytics.rs
  crates/meilisearch/src/lib.rs
  crates/meilisearch/src/option.rs
Labels: experimental feature, no db change

#5565 Fix 0 batched task
  crates/index-scheduler/src/lib.rs
  crates/index-scheduler/src/scheduler/snapshots/test.rs/test_scheduler_doesnt_run_with_zero_batched_tasks/after_restart.snap
  crates/index-scheduler/src/scheduler/snapshots/test.rs/test_scheduler_doesnt_run_with_zero_batched_tasks/registered_task.snap
  crates/index-scheduler/src/scheduler/test.rs
  crates/index-scheduler/src/test_utils.rs
Labels: bug, experimental feature, no db change

#5577 Comment out swarmia deployment for now
  .github/workflows/publish-docker-images.yml
Labels: no db change

#5578 perf: Faster index::get_index IT tests
  crates/meilisearch/tests/index/get_index.rs
Labels: maintenance, no db change

#5580 tests: Assert succeeded/failed for the index::delete_index IT tests
  crates/meilisearch/tests/index/delete_index.rs
Labels: maintenance, no db change

#5573 Only intern in case of typo when looking for one or two typoes
  crates/milli/src/search/new/query_term/compute_derivations.rs
Labels: no db change

#5557 Update charabia v0.9.5
  Cargo.lock
  crates/milli/Cargo.toml
Labels: no db change

#5548 Added support for nested wildcards to attributes_to_search_on
  crates/meilisearch/tests/search/restrict_searchable.rs
  crates/milli/src/attribute_patterns.rs
  crates/milli/src/search/new/mod.rs
Labels: no db change

#5541 Minor fixes: Deactivate numbers in typos
  crates/meilisearch/tests/search/mod.rs
  crates/milli/src/disabled_typos_terms.rs
  crates/milli/src/update/new/indexer/post_processing.rs
  crates/milli/src/update/settings.rs
  crates/milli/src/update/upgrade/v1_15.rs
Labels: skip changelog, no db change

#5593 Remove TemplateChecker
  crates/milli/src/prompt/error.rs
  crates/milli/src/prompt/mod.rs
  crates/milli/src/prompt/template_checker.rs
Labels: no db change

#5584 tests: Faster index::search::mod IT tests
  Cargo.lock
  crates/meili-snap/Cargo.toml
  crates/meili-snap/src/lib.rs
  crates/meilisearch/tests/auth/api_keys.rs
  crates/meilisearch/tests/common/mod.rs
  crates/meilisearch/tests/search/errors.rs
  crates/meilisearch/tests/search/filters.rs
  crates/meilisearch/tests/search/mod.rs
Labels: no db change

#5574 perf: Faster integration tests for add_documents.rs
  Cargo.lock
  crates/meili-snap/Cargo.toml
  crates/meili-snap/src/lib.rs
  crates/meilisearch/Cargo.toml
  crates/meilisearch/tests/documents/add_documents.rs
Labels: maintenance, no db change

#5592 Decouple geo facet extraction from rest of document
  crates/milli/src/update/new/extract/faceted/extract_facets.rs
  crates/milli/src/update/new/extract/faceted/facet_document.rs
Labels: no db change
