Repository meilisearch/meilisearch, pull requests merged in 2025-06, with the labels that each got.

#5599 tests: Faster search::errors IT tests
  crates/meilisearch/tests/search/errors.rs
Labels: no db change

#5601 tests: Faster search::locales IT tests
  crates/meilisearch/tests/search/locales.rs
Labels: no db change

#5602 tests: Faster search::matching_strategy IT tests
  crates/meilisearch/tests/search/matching_strategy.rs
Labels: no db change

#5609 tests: Faster settings::proximity_settings IT tests
  crates/meilisearch/tests/settings/proximity_settings.rs
Labels: no db change

#5610 tests: Faster settings::tokenizer_customization IT tests
  crates/meilisearch/tests/settings/tokenizer_customization.rs
Labels: no db change

#5618 tests: Faster vector::binary_quantized IT tests
  crates/meilisearch/tests/vector/binary_quantized.rs
Labels: maintenance, no db change

#5620 tests: Faster search::distinct IT tests
  crates/meilisearch/tests/search/distinct.rs
  crates/meilisearch/tests/search/snapshots/distinct.rs/distinct_at_search_time/succeed.snap
Labels: maintenance, no db change

#5623 tests: Faster search::geo IT tests
  crates/meilisearch/tests/common/mod.rs
  crates/meilisearch/tests/search/geo.rs
Labels: maintenance, no db change

#5625 tests: Faster search::hybrid IT tests
  crates/meilisearch/tests/search/hybrid.rs
Labels: maintenance, no db change

#5632 ci: Use `GITHUB_TOKEN` secret for the `db change check` workflow
  .github/workflows/db-change-missing.yml
Labels: maintenance, no db change

#5615 tests: Faster tasks::mod IT tests
  crates/meilisearch/tests/common/mod.rs
  crates/meilisearch/tests/tasks/mod.rs
Labels: maintenance, no db change

#5635 Prompt for Email
  Dockerfile
  crates/meilisearch/src/analytics/mod.rs
  crates/meilisearch/src/analytics/segment_analytics.rs
  crates/meilisearch/src/main.rs
  crates/meilisearch/src/option.rs
Labels: no db change

#5642 chore: Fix English grammar in SearchQueue's comments
  crates/meilisearch/src/search_queue.rs
Labels: maintenance, no db change

#5611 tests: Faster stats::mod IT tests
  crates/meilisearch/tests/stats/mod.rs
Labels: maintenance, no db change

#5617 fix(milli/search): Cyrillic has different typo tolerance due to byte counting bug
  crates/meilisearch/tests/search/locales.rs
  crates/milli/src/search/new/query_term/parse_query.rs
Labels: no db change

#5660 Searchable fields aren't indexed when I add and remove them out of filterableAttributes
  crates/meilisearch/tests/search/mod.rs
  crates/milli/src/update/index_documents/extract/extract_docid_word_positions.rs
Labels: bug, no db change

#5668 Various fixes to embedding regeneration
  crates/milli/src/update/new/extract/vectors/mod.rs
Labels: no db change

#5672 docs: Recommend using a custom path for the benches' data
  CONTRIBUTING.md
Labels: maintenance, no db change

#5674 Bring back v1.15.2 to main
  Cargo.lock
  Cargo.toml
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/after_processing_everything.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/register_automatic_upgrade_task.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/registered_a_task_while_the_upgrade_task_is_enqueued.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/upgrade_task_failed.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/upgrade_task_failed_again.snap
  crates/index-scheduler/src/scheduler/snapshots/test_failure.rs/upgrade_failure/upgrade_task_succeeded.snap
  crates/meilisearch-types/src/features.rs
  crates/meilisearch/src/routes/chats/chat_completions.rs
  crates/meilisearch/src/routes/chats/config.rs
  crates/meilisearch/src/routes/chats/errors.rs
  crates/meilisearch/tests/search/mod.rs
  crates/meilisearch/tests/upgrade/mod.rs
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterEnqueuedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterFinishedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/batches_filter_afterStartedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterEnqueuedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterFinishedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/tasks_filter_afterStartedAt_equal_2025-01-16T16_47_41.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/the_whole_batch_queue_once_everything_has_been_processed.snap
  crates/meilisearch/tests/upgrade/v1_12/snapshots/v1_12_0.rs/check_the_index_scheduler/the_whole_task_queue_once_everything_has_been_processed.snap
  crates/milli/src/update/index_documents/extract/extract_docid_word_positions.rs
  crates/milli/src/update/new/extract/vectors/mod.rs
Labels: no db change

#5682 tests: Faster documents::update_documents IT tests
  crates/meilisearch/tests/documents/update_documents.rs
Labels: maintenance, no db change

#5677 tests: Faster document::errors IT tests
  crates/meilisearch/tests/documents/errors.rs
Labels: maintenance, no db change

#5681 tests: Faster settings::prefix_search_settings IT tests
  crates/meilisearch/tests/settings/prefix_search_settings.rs
Labels: maintenance, no db change

#5697 tests: Use Server::wait_task() instead of Index::wait_task() in documents::
  crates/meilisearch/tests/documents/add_documents.rs
  crates/meilisearch/tests/documents/delete_documents.rs
  crates/meilisearch/tests/documents/get_documents.rs
  crates/meilisearch/tests/documents/update_documents.rs
Labels: maintenance, no db change

#5708 Remove Gemini from the LLM-providers list
  crates/meilisearch-types/src/features.rs
  crates/meilisearch/src/routes/chats/config.rs
  crates/meilisearch/src/routes/chats/settings.rs
Labels: no db change

#5707 Add last embedder error in batches
  .gitignore
  crates/benchmarks/benches/indexing.rs
  crates/benchmarks/benches/utils.rs
  crates/dump/src/lib.rs
  crates/fuzzers/src/bin/fuzz-indexing.rs
  crates/index-scheduler/src/insta_snapshot.rs
  crates/index-scheduler/src/queue/batches.rs
  crates/index-scheduler/src/scheduler/process_batch.rs
  crates/index-scheduler/src/scheduler/process_index_operation.rs
  crates/index-scheduler/src/utils.rs
  crates/meilisearch-types/src/batch_view.rs
  crates/meilisearch-types/src/batches.rs
  crates/meilisearch/src/lib.rs
  crates/meilisearch/tests/vector/rest.rs
  crates/milli/src/progress.rs
  crates/milli/src/search/new/tests/integration.rs
  crates/milli/src/test_index.rs
  crates/milli/src/update/index_documents/extract/extract_vector_points.rs
  crates/milli/src/update/index_documents/extract/mod.rs
  crates/milli/src/update/index_documents/mod.rs
  crates/milli/src/update/new/extract/vectors/mod.rs
  crates/milli/src/update/new/indexer/extract.rs
  crates/milli/src/update/new/indexer/mod.rs
  crates/milli/src/update/settings.rs
  crates/milli/src/vector/composite.rs
  crates/milli/src/vector/mod.rs
  crates/milli/src/vector/ollama.rs
  crates/milli/src/vector/openai.rs
  crates/milli/src/vector/rest.rs
  crates/milli/tests/search/distinct.rs
  crates/milli/tests/search/facet_distribution.rs
  crates/milli/tests/search/mod.rs
  crates/milli/tests/search/phrase_search.rs
  crates/milli/tests/search/query_criteria.rs
  crates/milli/tests/search/typo_tolerance.rs
Labels: no db change
